### ISSUE TITLE
agent.getTimeline Headers Typescript Error

### ISSUE THREAD

**Issue by knightspore** [bluesky-social/atproto#1029]
When trying to add headers when fetching a user's timeline, the type hints suggest that one should format the call as follows: 

```ts
const { data } = await agent.getTimeline(
  {
    limit: 10,
  },
  {
    headers: {
      Authorization: `Bearer ${jwt}`,
    }
  }
``` 

However, when doing so network errors indicate the headers were not correctly added to the request.

Serializing the headers seems to work, although it presents a type error:

```ts
const { data } = await agent.getTimeline(
  {
    limit: 10,
  },
  {
    // Type 'string' is not assignable to type 'Headers'. (tsserver 2322)
    headers: JSON.stringify({
      Authorization: `Bearer ${jwt}`,
    })
  }
``` 

I'm not entirely sure how best to investigate further, but open to any recommendations.

**Comment by devinivy** [comment]
Ah, weird!  In general that should work, I'm sure there's just something small going wrong.

> However, when doing so network errors indicate the headers were not correctly added to the request.

Is the `Authorization` header you added omitted or does if have the wrong value?

Also, are you using `agent.login()`?  I ask because the agent will also try to manage that header when you have a session (i.e. by using `agent.login()`).

Lastly, could you try lower-casing the header as `authorization` and let us know if that helps?

**Comment by knightspore** [comment]
Hey @devinivy thanks for these pointers! I've tried to replicate with some of your suggestions included - and it seems that your last case was spot on!

```ts
// Returns Feed ✅
headers: {
  authorization: `Bearer ${key}`
}
```

```ts
// Error: Token could not be verified ❌
headers: {
  Authorization: `Bearer ${key`
}
```

**Comment by knightspore** [comment]
I've noticed in `@atproto/packages/api/tests/agent.test.ts` that the tests target "`httpHeaders.authorization`" (Lines 188, 253, 354), as well as the agent itself always using lowercase references. While headers should be case insensitive, I'm pretty sure this is what's causing this error.

**Comment by knightspore** [comment]
Thanks! I've tried a few times to patch my local package to see if I can find a working fix, but I'm not able to get the tests running properly. 

However it seems the source is the `getToken()` function in `pds/src/auth.ts`

https://github.com/bluesky-social/atproto/blob/a7c2b4ae119ee926cec48b67c95dbe15da59582a/packages/pds/src/auth.ts#LL129C1-L133C4

**Comment by Matrix89** [comment]
> However it seems the source is the `getToken()` function in `pds/src/auth.ts`

I've written a test for this and it passes, which makes sense according to the [docs](https://nodejs.org/api/http.html#messageheaders) headers are already lower-cased when entering `getToken()`

Investigating further rn

**Comment by Matrix89** [comment]
@knightspore I can't reproduce you the problem, can you share more details?

**Comment by knightspore** [comment]
> I've written a test for this and it passes

@Matrix89  it's possible I'm barking up the wrong tree there as I assumed it might already be lower-cased. 

I've put together [a simple example here](https://github.com/knightspore/bsky-authheader-example) - just install the deps and run `node index.js` and you should see it error out on line 29 where we use a capital "A".

**Comment by Matrix89** [comment]
So the issue is that you're adding the auth header yourself after calling `agent.login` which means the `authorization` header is added to the request twice.
This will be an easy fix(@devinivy is lower casing all the headers a accepted solution?), but when looking through node docs I've found some confusing behavior, more [here](https://github.com/Matrix89/node-joinDuplicateHeaders)

**Comment by knightspore** [comment]
Thanks so much @Matrix89, I understand much better now what's happening. I do recall seeing double Auth headers at some point but I wasn't able to replicate it (or at least didn't realise that's what I was doing in the above example). 

That is some confusing behaviour indeed - I'll be interested to follow along and see how it's solved.
