### ISSUE TITLE
Is `action` required in `com.atproto.repo.applyWrites`?

### ISSUE THREAD

**Issue by myConsciousness** [bluesky-social/atproto#1037]
Hi amazing developers,

I was looking at the `com.atproto.repo.applyWrites` lexicon and noticed that `action` is there as required. But none of the `create`, `update`, or `delete` definitions have `action` in their properties.

https://github.com/bluesky-social/atproto/blob/bba1ba739eac67dcacbea873f76823e8a94c1891/lexicons/com/atproto/repo/applyWrites.json#L39-L66

I have confirmed that this `action` was used before the refactoring of the protocol. Maybe forgot to erase it, or maybe it was left there for some reason?

**Comment by Matrix89** [comment]
> Maybe forgot to erase it

This seems to be the case, lexicon validator doesn't raise an error when there's a required property is missing from the properties definitions.

**Comment by dholms** [comment]
yup that's right. Thanks for the catch! it didn't get properly cleaned up in the lex refactor

**Comment by Matrix89** [comment]
@dholms #1040 Closes this one
