### ISSUE TITLE
How can I get the "identifier" to use with xrpc/com.atproto.server.createSession?

### ISSUE THREAD

**Issue by GreenFootballs** [bluesky-social/atproto#1052]
I'm just beginning to put together a simple API test script to cross-post from my personal site to Bluesky, using cURL.

But my first attempt fails when I POST to `https://bsky.social/xrpc/com.atproto.server.createSession` to get an access token. It returns a 401 error: "AuthenticationRequired - Invalid identifier or password".

The password I'm using is an app password created in Bluesky's settings. For the identifier, I'm using my Bluesky handle, @greenfootballs.bsky.social, and I think this is the problem. Do I need to call some other endpoint first to get the identifier?

**Comment by devinivy** [comment]
Just drop the `@` on your handle, and you should be all set!  You can use your handle (without the `@`) or your email address as the identifier.

**Comment by GreenFootballs** [comment]
Wow, I thought I had tried that already but I just gave it another shot, and there are the tokens. Thanks!
