### ISSUE TITLE
`com.atproto.sync.subscribeRepos` doesn't include a did of a post

### ISSUE THREAD

**Issue by lamrongol** [bluesky-social/atproto#1059]
We can get "firehose" of Bluesky but `subscribeRepos` doesn't include a did of a post, even includes `text`,  `createdAt`, `embed`, `reply` and so on.
So we can't know who post it.

**Comment by Matrix89** [comment]
I might be missing something but there's a `repo` field which should currently basically be the person who posted

**Comment by devinivy** [comment]
Yep, that's right!  Commit events contain a property `repo` containing the DID of the repository.

**Comment by lamrongol** [comment]
Sorry, I referred to http://whenitrains.glitch.me/script.mjs but could not find the `repo` field even after expanding `record`. Please let me know if I am missing something or if I can't get it by connecting to `wss://bsky.social/xrpc/com.atproto.sync.subscribeRepos`.

**Comment by Matrix89** [comment]
From your link
```ts
    const [header, body] = decodeMultiple(new Uint8Array(messageBuf))
```
`body.repo` contains the did

**Comment by lamrongol** [comment]
Oh, Thank you for your kind explanation.
