### ISSUE TITLE
Posts with images not published to firehose

### ISSUE THREAD

**Issue by dylanjt** [bluesky-social/atproto#1065]
I was testing feed-generator and it looks like the firehose is not publishing posts that have images.

Reproduce:
1. Clone https://github.com/bluesky-social/feed-generator
2. Modify src/subscription.ts,
```ts
// comment out line 16:
// console.log(post.record.text)

// line 23 (the postsToCreate filter condition)
return create.author === 'YOUR_DID'

// line 27 (in the postsToCreate map function)
console.log(create)
```

Run feed-generator in your terminal, and from your account add two new posts: one with an image and one without. Your terminal will only print the post without an image. Likewise, if you run the feed generator with no modifications and just watch the posts roll through, you'll notice no post will ever have an `embed.image` array.

**Comment by dholms** [comment]
95% sure this is an issue with the feed-generator codebase processing the firehose & not the outgoing firehose itself. looking into it more!

**Comment by dylanjt** [comment]
@dholms I did a cursory look through the feed generator code and couldn't find anything that appeared to filter the query to or data from the firehose. Sorry if I jumped the gun opening this issue here! Happy to close and reopen on the feed generator repo if that makes the most sense. Thank you for looking into it!

**Comment by dholms** [comment]
Nope no worries! We can leave it here 👌 

I just see that events _are_ coming through for posts with imgs in them but not getting properly parsed. So not impossible it's on the producer side

**Comment by dholms** [comment]
yup this was a goofy bug in the feed-generator code

fixed & merged here
