### ISSUE TITLE
Setting a post thumb to a string instead of a blob ref permanently disables the user account

### ISSUE THREAD

**Issue by waxpancake** [bluesky-social/atproto#1089]
Setting the image thumb for a post to a string (e.g. an image URL) via XRPC, instead of passing a blob ref, will permanently disable a user's account, corrupting the repo and leaving it in a read-only state where all writes fail with "500 Internal Server Errors" from both the web app and via XRPC. Posts, likes, replies, deletes, and profile edits all fail with 500 errors. (Logging in, reading posts, and creating app passwords all still function properly.)

Trying to rebase with an authenticated request to the com.atproto.repo.rebaseRepo endpoint will also fail with the same 500 error.

Some speculation from @DavidBuchanan314: "A commit seems to have been interrupted mid-commit (as far as I can tell), so the 'head' pointer is pointing at blocks that do not exist. Probably due to error handling happening at the wrong time." Dumping the repo results in an "an invalid CAR because the 'root' points to a block that is not contained within the CAR."

My account here is currently stuck in this state, if anyone with admin access wants to debug further:

DID: did:plc:l6vfwg5gvscvnmv5xfp4clol

**Update:** Edited the issue to better reflect the problem. See comments below for reproducible test case.

**Comment by DavidBuchanan314** [comment]
`did:plc:xuhbtg3cju5cwz57gthjtyu6` is another example of an account in this state, partial details in this thread https://bsky.app/profile/spv.sh/post/3jvn3cw7x2g2r (it would appear that image uploads are a common factor here)

**Comment by dholms** [comment]
Hey @waxpancake when was the request that you made that caused this?

We did have some issues with leaky transactions but fixed this a few weeks back. 

I'll look into these couple of particular cases here soon

**Comment by waxpancake** [comment]
@dholms It was last Friday, May 19. I posted [this message](https://bsky.app/profile/waxy.org/post/3jw4kyuzafc2x) warning followers that they'd see some test posts from the account while I was debugging it, I was able to post/delete a couple of tests successfully, and then it was nothing but 500 messages after that. 

The last successful request I can see in my logs is a POST to the `com.atproto.repo.uploadBlob` endpoint that returned the link ref `bafkreihtupdlitnktf65zijpi63gn7cni7ltckbwdwta5yizhqbumgy2rq`, an image/png of size 5217, if that helps at all. Every attempted write after that fails with a 500.

**Comment by waxpancake** [comment]
In case it's helpful, this is a JSON representation of the post data I attempted immediately after the image upload, which failed with a 500 error:
https://gist.github.com/waxpancake/d6c044af77e3dd8365573d43566baf6c

**Comment by DavidBuchanan314** [comment]
We have a reproducible test case (and my test account is now in a similar broken state, heh)

```
r = s.repo_create_record("app.bsky.feed.post", {
	"$type": "app.bsky.feed.post",
	"createdAt": get_timestamp(),
	"text": "test",
	"embed": {
		"$type": "app.bsky.embed.external#main",
		"external": {
			"$type": "com.example.unchecked",
			"uri": "https://example.com/",
			"title": "title",
			"description": "description",
			"thumb": "blah"
		}
	},
})
```

It would appear that `"$type": "app.bsky.embed.external#main"` causes lexicon validation for the "thumb" field to get skipped. With it set to just `app.bsky.embed.external`, I get a more expected error:

```
{"error":"InvalidRequest","message":"Invalid app.bsky.feed.post record: Record/embed/external/thumb should be a blob ref"}
```

**Comment by waxpancake** [comment]
@dholms Looks like we narrowed this down to a reproducible bug. Let us know if you need any more info... and of course, I'd love to know if my account can be restored somehow!

**Comment by Matrix89** [comment]
For anybody investigating exception in `verifyBlobAndMakePermanent` because `blob2.cid` is undefined
![image](https://github.com/bluesky-social/atproto/assets/5559081/0241d5eb-7dd5-41ae-b111-f85a1c6dce9a)

**Comment by DavidBuchanan314** [comment]
It would appear that the malformed `app.bsky.embed.external#main` object is able to pass through this assertValidRecord check https://github.com/bluesky-social/atproto/blob/85bcd18a7b74908b48e1505737d3b7857772860c/packages/pds/src/repo/prepare.ts#L178

**Comment by Matrix89** [comment]
@DavidBuchanan314  
> while also passing the isExternalEmbed check here 

Only checks the `$type` field it doesn't validate the object

But I think `assertValidRecord` should handle this

**Comment by DavidBuchanan314** [comment]
Ok there's at least 2 bugs here, I think.

Bug 1: malformed embed object passes lexicon validation. This is due to the open union check not also checking for the `#main` suffix, and thus treating `app.bsky.embed.external#main` as not an explicit member of the union

https://github.com/bluesky-social/atproto/blob/85bcd18a7b74908b48e1505737d3b7857772860c/packages/lexicon/src/util.ts#L44-L53

Bug 2: The exception that happens during `verifyBlobAndMakePermanent` should ideally cause the relevant db transaction to be rolled back, but that's not happening for some reasons

**Comment by Matrix89** [comment]
Yep, I guess this also shows the first issue really well
![image](https://github.com/bluesky-social/atproto/assets/5559081/1fe842da-be15-464f-8298-b4e80232701d)

**Comment by dholms** [comment]
Alright @waxpancake I manually rolled back your repo by one commit so it should be unborked now 👍 

@DavidBuchanan314 that's exactly right with the issues. This appears to be a leaky transaction which we have some mechanisms in place to stop but they don't appear to be working here. I'll continue the bug fixing

If there are any other repos that are currently in a borked state & you need me to manually fix please let me know

**Comment by DavidBuchanan314** [comment]
Thank you, my affected repo is `did:plc:b2wskpxho4srwilqyssafllz`

**Comment by waxpancake** [comment]
@dholms Perfect, thank you!

**Comment by dholms** [comment]
kk fixed yours as well @DavidBuchanan314 (just rolled back to prev commit)

**Comment by waxpancake** [comment]
@dholms Sadly, my repo is once again in a broken read-only state. Like before, any attempt to post with the web app, iOS app, or API all return 500 Internal Server Errors with no additional information.

My repo is `did:plc:l6vfwg5gvscvnmv5xfp4clol` if you wouldn't mind taking a look. Alternately, I can try rebasing myself, but I didn't want to make debugging this harder.

Unlike before, I wasn't setting the post thumb to a string and I'm not sure exactly what triggered it this time. The post that apparently broke it was this one, which seems pretty standard. I don't see any possible issues, except maybe the control characters in the description — I'll strip newlines out in the future if that's ultimately the problem.

```
{
    "repo": "did:plc:l6vfwg5gvscvnmv5xfp4clol",
    "collection": "app.bsky.feed.post",
    "record": {
        "$type": "app.bsky.feed.post",
        "text": "Day of the Devs Summer Game Fest 2023: amazing showcase of upcoming indie games, personal highlights include Viewfinder, Summerhill, and Simpler Times https://www.youtube.com/watch?v=yqpcF-Q4enc",
        "createdAt": "2023-06-08T22:50:02Z",
        "facets": [
            {
                "features": [
                    {
                        "uri": "https://www.youtube.com/watch?v=yqpcF-Q4enc",
                        "$type": "app.bsky.richtext.facet#link"
                    }
                ],
                "index": {
                    "byteStart": 151,
                    "byteEnd": 194
                }
            }
        ],
        "embed": {
            "$type": "app.bsky.embed.external#main",
            "external": {
                "$type": "app.bsky.embed.external#external",
                "uri": "https://www.youtube.com/watch?v=yqpcF-Q4enc",
                "title": "Day of the Devs Summer Game Fest Edition 2023",
                "description": "Double Fine and iam8bit present Day of the Devs. Tune in right after Summer Game Fest for  a showcase of upcoming indie games!^M^M#gaming #sgf2023 #dayofthedevs",
                "thumb": {
                    "$type": "blob",
                    "ref": {
                        "$link": "bafkreidmnomz2lqrpsygdo4nl5af7rrrqqmledqctmpvzxcrbemrikpd3e"
                    },
                    "mimeType": "image/jpeg",
                    "size": 89512
                }
            }
        }
    }
}
```

**Comment by DavidBuchanan314** [comment]
@waxpancake @dholms my test2.retr0.id account is also broken again, but I don't think I did anything in particular to trigger it. I wonder if there was some latent database inconsistency which wasn't quite fixed up the first time?
