### ISSUE TITLE
provide containerized setup

### ISSUE THREAD

**Issue by simevo** [bluesky-social/atproto#110]
some people may have trouble installing ADX because of node >= 15 requirement, besides keeping 4 terminals open to run the demo is complex

using docker-compose would simplify the install & allow to run the demo with just two terminals

**Comment by simevo** [comment]
I have a WIP but at the moment the command to register bob is failing :blush:

**Comment by dholms** [comment]
Hopefully we can remove the >=15 requirement. That's from [ts-ucan](https://github.com/ucan-wg/ts-ucan) & I forget what actually requires the version 🤔 a bit of investigation is needed

I think we'll refrain from publishing a containerized setup until we have a piece of software that we actually want folks to host. A container for a demo seems to be overkill to me.

If you don't want server terminals open, you can always run it in the background with:
`yarn server > log.txt &`

& kill the process by getting the PID with
`sudo lsof -i :2583` (or whatever port it's on), followed by
`kill ${PID}`

**Comment by simevo** [comment]
makes sense!

BTW `ts-uscan` requires node >=15 because it uses the [webcrypto.subtle API](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) which is only available from node 15 onwards (I tried downgrading and launching the tests with `jest` but some tests failes due to that)

**Comment by dholms** [comment]
Ah yup that was it! Thanks for the quick investigation. We actually don't use the webcrypto API (we're focusing on Ed25519 keys right now which are not available in WebCrypto). I've been chatting with the Fission team about the possibility of removing the dependency on WebCrypto & having the consumer inject it themselves.

We'll see 🙂

**Comment by simevo** [comment]
anyway I got this far: https://github.com/simevo/adx/tree/issue-110-containerization

and now I know why the "register bob" step keeps failing: because the hostname of the `did-network` is hardwired to `localhost` here: https://github.com/bluesky-social/adx/blob/main/common/src/network/util.ts#L43

this cannot work, in `server1` and `server2` I need to replace that with `server1`!

**Comment by simevo** [comment]
aaah there's env var `DID_NETWORK_URL` for that ! now it works

**Comment by dholms** [comment]
Yup good looking 👌 

It's a bit hacky to run the DID network on the data server for this piece, but i decided to do that so that you wouldn't need to run _five_ servers for the demo. So we use the `DID_NETWORK_URL` to establish one particular point to go for DID queries, just like in the real network.

**Comment by simevo** [comment]
that's easy to do in the `docker-compose.yaml`, see https://github.com/simevo/adx/commit/7a91cb3058c98085b08391dc2dbc259b35d5c4c5
