### ISSUE TITLE
Will app password authentication continue?

### ISSUE THREAD

**Issue by GreenFootballs** [bluesky-social/atproto#1115]
I was told that you folks are working on implementing oAuth, which is great. But when oAuth rolls out, will the app password feature of Bluesky still work or will oAuth replace it?

**Comment by dholms** [comment]
I'm not totally sure to be honest.

OAuth should suffice for most usecases, but there may still be some use to app passwords. As an example, Apple supports both.

If we do decide to deprecate them, we won't do it over night, we'd phase them out

**Comment by dholms** [comment]
Also for future reference, we try to keep Issues focused on bug reports & features.

Discussions & questions like this are encouraged to happen over in the [Discussions](https://github.com/bluesky-social/atproto/discussions) tab :)

Closing for now
