### ISSUE TITLE
Can't post videos or gifs

### ISSUE THREAD

**Issue by TodePond** [bluesky-social/atproto#1162]
**Is your feature request related to a problem? Please describe.**

I'm sad when I can't post work-in-progress clips of things I'm working on. I'm stuck with posting them on twitter or mastodon instead.

eg: https://twitter.com/TodePond/status/1547200031161257986
eg: https://elk.zone/universeodon.com/@TodePond/110475890223132158

**Describe the solution you'd like**

I would like to be able to upload gifs and videos when I post (not just images).

**Describe alternatives you've considered**

I've also tried linking to gifs+videos, so that they embed within the feed - but this isn't supported yet.

**Additional context**

There was an old issue about this (#519) , which was closed. So I thought I would write it out fully using the new issue templates - so that it can be properly considered.

**Comment by ianklatzco** [comment]
i wonder if it would be possible to do video embeds in-app, like how vxtwitter displays video directly in telegram but not discord.

**Comment by HeyItsLollie** [comment]
I've been hoping for external embeds at the very least: YouTube, Imgur, SoundCloud, Sketchfab, etc. If I could add a link as a card, and then have that card load the embedded player in the post itself, that would really help open things up.

**Comment by devinivy** [comment]
Head on over to https://github.com/bluesky-social/atproto/discussions/1157 to continue the convo 👍

**Comment by TodePond** [comment]
![Screenshot_20230913-062751](https://github.com/bluesky-social/atproto/assets/15892272/01291871-3985-4b2a-baeb-08722ca566e1)

Hi! You've closed this as completed but it doesn't seem to be completed. Did you mean to close as not-planned? If that's the case, is it not planned? You've linked to a discussion which suggests it's not 👍

**Comment by devinivy** [comment]
The completed/planned state of gif support hasn't changed in any way, just trying to ensure all conversations around the feature are happening in one place 🙂

**Comment by TodePond** [comment]
Oh ok maybe best to keep it as an open issue then, so that people can see that there's an open issue for it?

**Comment by jack652** [comment]
> The completed/planned state of gif support hasn't changed in any way, just trying to ensure all conversations around the feature are happening in one place 🙂

so it's not completed then

**Comment by sayore** [comment]
Why is this closed?
