### ISSUE TITLE
Is the example regarding NSID "com.example.*" correct?

### ISSUE THREAD

**Issue by kjarex** [bluesky-social/atproto#1163]
Is the given example https://github.com/bluesky-social/atproto/blob/bf4ac79cef9ce36113ac9daae65c1315983ee263/packages/nsid/README.md?plain=1#L18-L20 correct?

Doesn't it trigger the `Disallowed characters in NSID (ASCII letters, digits, dashes, periods only)` error? So lines 19 and 20 shouldn't be possible? 

Similar I would expect the later example regarding `isValid` for `com.example.*` to result in `false`, too!?

**Comment by dholms** [comment]
Actually I believe that's right. We used to allow a wildcard as the name but have locked it down since then.

Verifying I have that right: @bnewbold any thoughts?

**Comment by bnewbold** [comment]
That is correct, we no longer accept "blob patterns" as a proper NSID. Specs (https://atproto.com/specs/nsid#nsid-syntax-variations) and implementation were updated, but I forgot to update this README. Will send over a quick PR for the README.
