### ISSUE TITLE
Repos getting into a broken state

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#1241]
Missed these comments since they were in a closed issue, so making a new issue to track

It appears some repos are still ending up in a broken state somehow:

https://github.com/bluesky-social/atproto/issues/1089#issuecomment-1588216632
https://github.com/bluesky-social/atproto/issues/1089#issuecomment-1606126911

**Comment by waxpancake** [comment]
Happy to help debug this however I can.

**Comment by dholms** [comment]
Okay I believe what happened here is:
- these repos got into a bad state in https://github.com/bluesky-social/atproto/issues/1089
- I "fixed" the repos by hand by rolling back the last commit
- however that commit was partially applied & the indexed record was sticking around
- when we did rebases a couple weeks back, we reconstruct a new MST using the record table
- we only garbage-collect on rebases, don't store any new blocks
- that record got factored into the MST giving you new MST blocks that didn't get stored
- so these repos are now missing blocks (even tho the bookkeeping of which blocks _should_ be there is actually correct 😅)

The fix is to ensure that we have all necessary blocks after rebase. I'll work on getting that in then can rebase both of these repos to get them into a good spot

**Comment by waxpancake** [comment]
@dholms Yay! When this change is live, can you rebase the did:plc:l6vfwg5gvscvnmv5xfp4clol repo? I'll turn my bot back on and hopefully everything will be good to go.

**Comment by dholms** [comment]
alright just rebased both repos & they're still in a bad (but different!) state. need to reinvestigate a bit 🧐

**Comment by dholms** [comment]
Alright finally fixed these!

Didn't require a code change, just manually cleaning up some side effects from a prev leaky tx bug.

Wrote a bit more here & planning some more defensive code for missing blocks: https://github.com/bluesky-social/atproto/issues/1280

Thanks for the patience yall 🙏

**Comment by waxpancake** [comment]
The repo's working again, thank you!

**Comment by DavidBuchanan314** [comment]
Just tested, my repo is also working again, ty
