### ISSUE TITLE
Creating new Node project results in compiler errors

### ISSUE THREAD

**Issue by aneillans** [bluesky-social/atproto#1259]
**Describe the bug**
Creating a new node project, and npm installing atproto/api results in multiple compiler errors with dependencies apparently not correctly exporting interfaces; for example from common-web and lexicon. Checking the interfaces exposed, they do appear to be lacking, but checking against the source I can see they are present - looks like maybe a published package issue? Confirmed latest versions installed as published. 

**To Reproduce**

1. Create new project
2. npm install atproto/api
3. Create basic ts file containing (as per the quick start):
import { BskyAgent } from '@atproto/api'

const agent = new BskyAgent({ service: 'https://bsky.social' })

agent.login({
  identifier: process.env.BLUESKY_USERNAME!,
  password: process.env.BLUESKY_PASSWORD!,
});

4. Compile; receive (for example)

node_modules/@atproto/api/dist/client/types/app/bsky/actor/profile.d.ts:1:28 - error TS2305: Module '"@atproto/lexicon"' has no exported member 'BlobRef'.

1 import { ValidationResult, BlobRef } from '@atproto/lexicon';
                             ~~~~~~~

node_modules/@atproto/api/dist/client/types/app/bsky/embed/external.d.ts:1:28 - error TS2305: Module '"@atproto/lexicon"' has no exported member 'BlobRef'.

1 import { ValidationResult, BlobRef } from '@atproto/lexicon';
                             ~~~~~~~

**Expected behavior**

No compiler errors

**Details**

 - Operating system: Win 11
 - Node version: 16 and 18

**Comment by joeltg** [comment]
This is happening because the packages here are developed in a monorepo but published ad-hoc/separately.

For example, `@atproto/api` in `v0.3.13` (published 12 days ago) tries to import `parseLanguage` from `@atproto/common-web`, which was added two weeks ago in [this](https://github.com/bluesky-social/atproto/commit/3da0324873063974e8ce6296e11f72848f1bf5b8) commit but hasn't been published to NPM (last version was `v0.1.0`... three months ago).

This means `@atproto/api` straight-up fails to compile:

```
node_modules/@atproto/api/dist/index.d.ts:3:10 - error TS2305: Module '""' has no exported member 'parseLanguage'.

3 export { parseLanguage } from '@atproto/common-web';
```

**Comment by joeltg** [comment]
For anyone else looking to fix compiler errors: as of today, you can get it all to work by downgrading `@atproto/api` to `v0.3.12` and downgrading `zod` to `v3.21.0` (`z.extendShape` was renamed in Zod `v3.21.1`).

**Comment by dholms** [comment]
Thanks for the report.

I re-published all the dependencies here so you should be good to go now. But let me know if you run into any further issues.

We're bundling code which means that you don't actually need the code from any of the out of date packages. What I didn't realize is that it didn't bundle in types which affects compilation
