### ISSUE TITLE
Block slurs as handles

### ISSUE THREAD

**Issue by jesslark** [bluesky-social/atproto#1317]
It would be prudent to increase safety for the most marginalized users by blocking slurs from being used as handles. To address this issue, I implemented a small change to the reserved words file. This list is not remotely close to exhaustive but is a good first step. I would appreciate attention given to this PR to improve the quality. Additionally, if this PR is merged quickly, as it should be, and further changes are needed, please comment and I will make additional PRs to improve the quality of the list.

PR: https://github.com/bluesky-social/atproto/pull/1314

**Comment by TheFeloniousMonk** [comment]
Merge the PR, BlueSky.

**Comment by dovesdeeply** [comment]
Please add: 1488, 88, HH, troon, roastie, boong (Australia), petrol sniffer (Australia), mowree/mowri (New Zealand), cannibal (Australia and New Zealand), barcode (New Zealand), scribble face or scribble chin (New Zealand), mongoloid, curry muncher, camel jockey, half-caste, cotton picker, golliwog, untermensch, wetback, peacefools, Muzzie (Australia), jihadi, Christ-killer, Palestinazim, cow piss drinker, piss drinker, Osama, hajji, hadji, haji, groomer, gin/jin (Australia), parasite, locust, monkey, savage, oven dodger, poofter, towel-head, wog, dogpill, femoid, foid, goy, goyim, landwhale.

Additionally these German phrases used by neo-Nazis: https://www.adl.org/resources/hate-symbol/german-phrases

**Comment by gay-frogs** [comment]
it was recommended that i post suggestions here.  i've appended the current live list to include ~140 new terms and variants, including quite a few from @dovesdeeply and some that others on bluesky mentioned.  i did as much diligence as i could and believe that each term on the list is (1) exceptionally derogatory, (2) has not been reclaimed, and (3) would not be used in a non-derogatory sense.

should follow formatting of original.  all compound terms contain hyphenated variants, all plural-applicable terms contain their pluralized variants as well.

the list can be viewed here: https://gist.github.com/gay-frogs/aaa6ead819b62a3538d95b1ded6e571a

**Comment by SlickDomique** [comment]
I opened additional PR that addresses ability to put slurs into a subdomain in the user handle. Here's the PR https://github.com/bluesky-social/atproto/pull/1320

**Comment by intrnl** [comment]
Ideally slurs and reserved names should be separated, reserved names doesn't have to be tested on user-provided domains, but slurs should still be checked.

Additionally it wouldn't be great for slurs to be in Set form like how it is now (where `string[]` gets converted to `Record<string, true>`, it should be kept as `string[]` where the validation could go something like:

```ts
const slurList: string[] = [];

const handle = '...';
const handleWithoutSeparators = handle.replace(/[.-]/g, '');

for (let idx = 0, len = slurList.length; idx < len; idx++) {
  if (handleWithoutSeparators.includes(slurList[idx])) {
    throw new Error('slur bad');
  }
}
```

**Comment by robotblake** [comment]
I wonder if having a list of blocked words (and common variations) as part of the integration tests might not be a terrible idea. That way whatever solution gets landed on (regex, hash table / set, etc) there'll be some confidence that changes aren't introducing regressions. It also would make it much easier to test new implementations in case there are concerns about speed / memory usage / etc.

**Comment by ghobs91** [comment]
This list may be helpful: https://github.com/abstraq/chat_filters/blob/main/filter_slurs.txt

**Comment by intrnl** [comment]
if I remember correctly Bluesky doesn't handle Unicode domains, but does it accept it in punycode? it might be necessary to handle that and then try to normalize it before doing the slur check

**Comment by robotblake** [comment]
On the `> ASCII` front https://github.com/Blank-Cheque/Slurs has some good regex examples for specific words too.

**Comment by HarryGogonis** [comment]
Suggestion to add unit tests or use an already-tested library. There is a lot of edge cases here such as permutations https://github.com/bluesky-social/atproto/pull/1326 as well as bad names embedded between https://github.com/bluesky-social/atproto/pull/1323

**Comment by simonblack** [comment]
> Suggestion to add unit tests or use an already-tested library. There is a lot of edge cases here such as permutations #1326 as well as bad names embedded between #1323

I think there merit to this, but I think there's far more value with building a list in-house, _specific_ to the brand. After a brief search for some of these prior to implementing #1326 and I'm positive that some of what libraries deem unacceptable, bsky users will deem to be censorship. 

Additionally, permutations and words embedded within names is the entirety of the edge cases here (apart from maybe custom domain slur checking, which i cannot confirm atm) they can be handled fairly simply combining both of the approaches, with the additional benefit of giving BlueSky trust and safety the ability to maintain their own censorship list based on the needs of the platform

All that said, there could very well be a better approach, I dont believe a third-party solution is it

cheers

**Comment by bnewbold** [comment]
This specific issue was closed in: https://github.com/bluesky-social/atproto/pull/1318

Ongoing discussion of more detection techniques (including soundex, regex, etc) should go here, so suggestions and references don't get lost: https://github.com/bluesky-social/atproto/discussions/1329

**Comment by SlickDomique** [comment]
@bnewbold I'm sorry, but it was not closed. It is still possible to change into a custom domain handle and have slur in every possible form. I address this and add better protection here https://github.com/bluesky-social/atproto/pull/1320

**Comment by monicaellerose** [comment]
Having the ability to not only prevent bad actors from usernames but to also include display names, and bios.

Having the ability to make it easy for users to submit words to add to this list 

Listening to the community if a word gets wrongly added to the ban word list which has happened  (on a few other circulating lists many lgbt reclaimed words appear on this list as an example https://github.com/abstraq/chat_filters/blob/main/filter_slurs.txt ) 
 
Separate the banned names list from the banned word list. 

I also support using basic regex to these words to prevent bad actors from adding /s/ers/ss/ies/its/  to the end of words, to make it that much more difficult for bad actors to harm community members.
