### ISSUE TITLE
Block slurs in feed names

### ISSUE THREAD

**Issue by azigler** [bluesky-social/atproto#1328]
Related to #1317, there is nothing preventing slurs from being used in feed names. Since many names on the reserved list *should* be allowed in a feed name (because they are domain-specific in many cases, not necessarily slurs), feeds should check against only the slur sub-list. This would improve safety and security for AT Protocol's most marginalized users.

If there are other user-facing fields, they should undergo a similar audit to ensure they cannot be used with slurs.

**Comment by HarryGogonis** [comment]
👍 add test cases for every user facing field

**Comment by WilliamRoyNelson** [comment]
> 👍 add test cases for every user facing field

I wrote a little bit about this in my own issue, #1337 but I think it's something that deserves a very thoughtful implementation.

As an example, it's probably fine to reject the use of "Nazi" in any handle, even cool ones like "NaziPunksFuckOff"
But for a curated block list, it's probably very useful to have a list named "Nazis and Nazi apologists" 

There probably should be at least one person who's entire job is figuring all this out.
