### ISSUE TITLE
Reserved words changes will over-write each other. 

### ISSUE THREAD

**Issue by jesslark** [bluesky-social/atproto#1334]
None of us will be pulling latest main from the last few minutes because we aren't responsible for handling our own checks and merges, and many of these PRs are being written at the same time. Whoever is approving and merging reserved words changes, please be cognizant of unintentionally removing words. Thank you!

**Comment by dholms** [comment]
We landed a change here that expands the list: https://github.com/bluesky-social/atproto/pull/1336

We opted to not leave the list public as it allows for bad actors to find loopholes in the flagging system. We check every report from the app and will use those to continue to inform the list

**Comment by jesslark** [comment]
That's an awesome revision! I hope we soon hear a more comprehensive response from leadership on the app. 

Thanks!!
