### ISSUE TITLE
Custom feeds: Support the user-facing URL

### ISSUE THREAD

**Issue by csuhta** [bluesky-social/atproto#1383]
It would be great if custom feed providers could optionally send the user-facing URLs `https://bsky.app/profile/<handle>/post/<id>` when sending feed items, instead of only the `at://` URL.

I am hacking on a feed provider with others, and translating between the two URL schemes is kind of a pain right now. (Non-technical people can only send you the website links)

One other thing that would really be nice is if there was a "Copy at:// link" on the user-facing website context menu for a post too

**Comment by dholms** [comment]
Records are canonically addressed by their at-uri. The user-facing URL in the application is purely a client construct and has no bearing on the data model of the network. Network services (like feed providers) must work with at-uris.

The mapping between these client uris & at-uris is well-defined & deterministic so it shouldn't be too difficult to write a simple tool to translate between them
