### ISSUE TITLE
External link CDN images return 422 after uploading through AtpServiceClient.uploadBlob

### ISSUE THREAD

**Issue by shawnphoffman** [bluesky-social/atproto#1389]
**Describe the bug**

I'm able to successfully call `uploadBlob`, get a valid response, and pass it as an `thumb` in an `'app.bsky.embed.external'` post. When the post loads, the images return HTTP 422 from the image proxy.

**Is it possible to debug uploaded blobs or image proxy failures?**

**To Reproduce**

1. Navigate to https://cdn.bsky.social/imgproxy/uPzX5tqsf54X1zoakMhfKT_odhG20K_pHKkI8qCIoeQ/rs:fit:1000:1000:1:0/plain/bafkreia3gco5llhsjwhqbvquhjz6zunzltbapqzs2ivvpowgxkjjmvgr54@jpeg 

**Expected behavior**

**Details**

 - Operating system: Mac OS X 13.4.1
 - Node version: v18.16.1

**Additional context**

- I'm sure there is something I'm doing wrong with the way I'm encoding the image for `uploadBlob`. I tested on image embed posts and got the same result.

**Comment by md1guy** [comment]
I'm having similar issue with images converted from svg using [sharp](https://sharp.pixelplumbing.com/). Other images are uploading/displaying just fine. @shawnphoffman Did you find a solution to this problem?


Example image: https://cdn.bsky.social/imgproxy/0em1FWuqVDz5FQeHVxUKGwGgYOe44TaKQjsi1c9t4FU/rs:fit:1000:1000:1:0/plain/bafkreifneg2ai5lzz6h5ahg3swfer7qlmbsh3sgbtve7k7s7r4kneinz2e@jpeg
