### ISSUE TITLE
Self Tagging Sensitive Content

### ISSUE THREAD

**Issue by ZigTag** [bluesky-social/atproto#1403]
**Is your feature request related to a problem? Please describe.**

There is some content and art which is not detected by the AI when deciding if a post is nsfw or not. Typically these posts aren't hidden even if they include a clear indication that they contain sensitive content

**Describe the solution you'd like**

Any post which contains the string "#nsfw" should be marked as sensitive

**Describe alternatives you've considered**

Allowing users to manually mark images or posts as sensitive.

**Additional context**

I really want to be able to use bluesky and some third party feeds without getting flash banged

P.S.

Please tell me if I should post this elsewhere but I'd assume it should be up to ATProto to moderate

**Comment by intrnl** [comment]
for ref.

https://github.com/bluesky-social/social-app/pull/1057#issuecomment-1656217199

> **Is self-labeling coming?** Yes, it's driving me crazy that it's taken so long to get done. I much prefer self-labeling.

**Comment by ZigTag** [comment]
Glad there is something coming to mitigate the issue, maybe I can rename the issue to make sure that people don't try reposting it
