### ISSUE TITLE
remove quotes of blocked users

### ISSUE THREAD

**Issue by monicaellerose** [bluesky-social/atproto#1448]
quotes of users i have blocked **show up** on my home timeline.

quotes of users I have muted  **do not show up** on my home timeline. 

the best scenario is to have this as an opt in under home feed settings, or have the ability to also hide quotes of users we have blocked. 
I dont know if this was fully a bug or an intended results, 

I feel that quotes of users we have blocked is probably more harmful than quotes of muted users. and  having those muted users be hidden is the best case scenario. 

the code responsible for finalizing the mute decision
https://github.com/bluesky-social/atproto/blob/5cc57d5ebce5af8c3082897b9ea83acabd395b3b/packages/api/src/moderation/accumulator.ts#L139-L142

the code responsible for actually filtering them out from the feed
https://github.com/bluesky-social/atproto/blob/5cc57d5ebce5af8c3082897b9ea83acabd395b3b/packages/api/src/moderation/index.ts#L176-L183

**Comment by pfrazee** [comment]
Fixed with https://github.com/bluesky-social/atproto/pull/1463 !
