### ISSUE TITLE
Feature: send emails about new logins

### ISSUE THREAD

**Issue by ryvwel** [bluesky-social/atproto#1530]
**Is your feature request related to a problem? Please describe.**

I love discord for this. Also, there is no 2FA yet, so i believe it would be some kind of security related

**Describe the solution you'd like**

I want to receive emails about new logins to my account, maybe with some information like user agent, ip, or even with option to terminate the session if it possible 

**Describe alternatives you've considered**

2FA

**Comment by kjarex** [comment]
While I like the idea in general, I would ask to make it optional/ possible to disable, please
