### ISSUE TITLE
Add account creation date property to app.bsky.actor

### ISSUE THREAD

**Issue by itsWindows11** [bluesky-social/atproto#1556]
**Is your feature request related to a problem? Please describe.**

Currently getting the account creation date depends on heuristics. It would be good to have a straightforward method to get the account creation date in the app.bsky.actor lexicon.

**Describe the solution you'd like**

Add a property `accountCreationDate` to either the basic or detailed profile view.

**Describe alternatives you've considered**

The heuristics I'm talking about, which is basically just getting the first action on a repo but this can be inaccurate.

**Additional context**

*No response*

**Comment by kjarex** [comment]
I'm not proposing against your request. Just as an alternative solution or workaround until something better might show up:

It's not part of the lexicon, but at least it's accurate and easily to get:
Query the appropriate plc.directory for the did's log/audit. Among other things it contains the creation timestamp (in <first object>.cid.createdAt)
