### ISSUE TITLE
getActorLikes should include like timestamp and should sort by that

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/atproto#1574]
**Is your feature request related to a problem? Please describe.**

Imagine the situation:

* one of the devs posts a real banger that I somehow miss
* in the year of our Lord 2027, I'm browsing Bluesky on my brand new Apple Vision Pro Series 3 and I come across someone reposting it; I press "like"
* the next morning, I remember about the post and I want to send it to a friend
* I open my "likes" tab, however, since the posts there are sorted by post creation date, not by like date, and this one is from 4 years ago, it will be positioned thousands of pages down, so I will never find it there

**Describe the solution you'd like**

* the items in the JSON returned from `getActorLikes` should include the `createdAt` timestamp of the *like* record
* the list should be sorted by that timestamp, so something that I liked a moment ago should be at the top of the list, even if it's a post from 4 years ago

**Comment by dholms** [comment]
Yup we did sort wrong on this & are gonna fix it 👍

**Comment by intrnl** [comment]
is this not because of the app sorting the timeline based on indexedAt? the API response itself is returning in the correct order

**Comment by mackuba** [comment]
👀

**Comment by mackuba** [comment]
IMHO it would make sense to also include that indexed date field in the JSON response, in case the client wants to use it e.g. for some kind of grouping, or for sorting later when it's persisted in some kind of local database etc.

**Comment by hyfen** [comment]
The sorting got fixed but nothing got added to the JSON response. I opened #3342 for that.
