### ISSUE TITLE
ListItemView doesn't have its own uri

### ISSUE THREAD

**Issue by gildaswise** [bluesky-social/atproto#1622]
**Is your feature request related to a problem? Please describe.**

I've implemented curated lists in [deck.blue](https://deck.blue) and it's mostly working fine, but for the removal process of a list item, I need to query the `app.bsky.graph.listitem` repo, check if any item matches the list I'm trying to manage, and then filter the related records just to get their ListItem uris to use with deleteRecord.

**Describe the solution you'd like**

This whole process would be easier and more performant if [ListItemView](https://github.com/bluesky-social/atproto/blob/17ce804ffaaafb1b1efb61174217a1da275feda8/lexicons/app/bsky/graph/defs.json#L41C6-L41C18) just had the uri property as its [Record](https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/graph/listitem.json) version does when returned by [listRecords](https://github.com/bluesky-social/atproto/blob/main/lexicons/com/atproto/repo/listRecords.json).

**Comment by intrnl** [comment]
feel like it might also be worthwhile for the getList endpoint to also *not* hide list items where the subject user no longer exists...

we can turn the ListItemView into the following
```
export interface ListItemView {
  uri: AtUri;
  did: DID;
  subject: ProfileView | null;
}
```
