### ISSUE TITLE
[Feature Request] Users should unfollow the account that blocked them

### ISSUE THREAD

**Issue by MedeHurGang** [bluesky-social/atproto#1731]
As a lot of people using blockchains which includes the follows of unwanted account. 
It would be very nice if an account that is blocked, would also unfollow the user that blocked that account.

**Comment by devinivy** [comment]
If one user blocks another then responses from `app.bsky.*` endpoints should no longer reflect any follow relationship between them.  If there's a case where this isn't handled we'd definitely want to know!  Can you give some details about where you're seeing a follow between blocked users?

**Comment by MedeHurGang** [comment]
seems to be fixed/implemented in between, i have seen this before in web app and ios app a few days ago. i haven't re-checked before opening this feature request, sorry for wasting your time. i will close ticket.
