### ISSUE TITLE
Contributor sign-offs on MIT+Apache2 license extension

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/atproto#1786]
We are planning to re-license this repository (`bluesky-social/atproto`) from straight MIT License to "MIT or Apache-2".

The main motivation for this change is to clarify that this source code is free and open in terms of *patents*, in addition to the existing *copyright* grants from the MIT license. This is an expansion of reuse rights; any downstream user of the source code can continue to use MIT-only if they like. You can read more about this specific license combination at https://protocol.ai/blog/announcing-the-permissive-license-stack/, and see an example atproto project with this license setup at https://github.com/did-method-plc/did-method-plc

I ran through the list of contributors to this repo (https://github.com/bluesky-social/atproto/graphs/contributors), and excluded Bluesky staff, contributions which were primarily text or documentation, and some short contributions. All those contributions are also appreciated! But don't want to spam everybody.

The remaining contributors are:

- [x] @jesopo
- [x] @43081j
- [x] @MaxGraey
- [x] @yafesdot
- [x] @Matrix89
- [x] @DavidBuchanan314

If you folks are OK with this license change and can reply to this github issue indicating as such, that would be much appreciated.

If not, that is also fine, and sorry for the noise. We might revert patches or find some other arrangement.

Either way, thanks again for your contributions!

**Comment by jesopo** [comment]
👌 go off my liege

(that's a yes from me)

**Comment by 43081j** [comment]
Sounds good to me 👍

**Comment by Matrix89** [comment]
I'm OK with this

**Comment by MaxGraey** [comment]
I'm ok with this

**Comment by yafesdot** [comment]
Sounds good 👍
(Sorry for the late response 😭)

**Comment by DavidBuchanan314** [comment]
LGTM :+1:

**Comment by bnewbold** [comment]
thanks again everybody!
