### ISSUE TITLE
In search queries, treat "from:@handle" the same way as "from:handle"

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/atproto#2028]
**Describe the bug**

The posts search allows filtering by post author using the "from:" keyword. However, it only works when the handle is passed without the "@". Since handles in the UI and in mentions are usually written with a leading "@", users are likely to put the handle with a "@" into the search - but this doesn't seem to work.

**To Reproduce**

Search results for "from:mackuba.eu swiftui":

<p><img width="602" alt="Screen Shot 2024-01-06 at 22 43 33" src="https://github.com/bluesky-social/atproto/assets/28465/d6bb6598-965b-4e18-9a76-175948c6e509"></p>

Search results for "from:@mackuba.eu swiftui":

<p><img width="602" alt="Screen Shot 2024-01-06 at 22 43 43" src="https://github.com/bluesky-social/atproto/assets/28465/812bf405-5b58-46c9-b7e6-9090f89e3932"></p>

**Expected behavior**

These two queries should return the same results.

**Comment by bnewbold** [comment]
If you want to take a whack at it, the specific code for this query parsing is in golang, in the indigo repo, here:

https://github.com/bluesky-social/indigo/blob/main/search/parse_query.go#L36

Unfortunately, we are in a state which makes deploying any change at all to the search system very difficult, and we have some other high-priority work in progress for a few more weeks, so even with working code this probably won't get updated for a bit.

**Comment by Hanaffi** [comment]
@bnewbold @mackuba  can you please assign it to me?
