### ISSUE TITLE
Consistently returning 500 errors

### ISSUE THREAD

**Issue by jordanreger** [bluesky-social/atproto#2046]
**Describe the bug**

Using the XRPC API through a simple JS script to retrieve followers, I receive a 500 error.

**To Reproduce**

1. Run the following with Deno (works in Node as well as it's basic JS):
```
const pd = { "identifier": "{did}", "password": "{app password}" };

const jwt = await fetch("https://bsky.social/xrpc/com.atproto.server.createSession", {
  method: "POST",
  body: JSON.stringify(pd),
  headers: { "Content-Type": "application/json" }
}).then(res => res.json().accessJwt);

const follows = await fetch(`https://bsky.social/xrpc/app.bsky.graph.getFollowers?actor=${encodeURIComponent(`at://${pd.identifier}`)}`, {
  headers: { "Authorization": `Bearer ${jwt}`}
});

console.log(follows);
```

**Expected behavior**

Returning list of follow records

**Details**

- Operating system: MacOS 14.2.1
- Node version: v20.5.1
- Deno version: 1.39.2

**Additional context**

Tried changing as many parameters as I could, such as removing `at://`, using a `com.atproto.repo.getRecord`, etc. - all returned 500 error.

**Comment by devinivy** [comment]
I am pretty sure the issue here is that the string `'undefined'` is getting passed as the jwt, since `res.json()` is a promise rather than the json itself.  I believe this diff should do the trick:

```diff
 const jwt = await fetch("https://bsky.social/xrpc/com.atproto.server.createSession", {
   method: "POST",
   body: JSON.stringify(pd),
   headers: { "Content-Type": "application/json" }
- }).then(res => res.json().accessJwt);
+ }).then(res => res.json()).then(json => json.accessJwt);
```

**Comment by jordanreger** [comment]
yep this worked, thanks... can't believe i didn't catch that haha

**Comment by devinivy** [comment]
Glad you got it going!
