### ISSUE TITLE
did:web accounts seem to be impossible to create right now

### ISSUE THREAD

**Issue by goeo-** [bluesky-social/atproto#2100]
**Describe the bug**

did:web is one of the blessed did types for atproto and currently there seems to be no way to make accounts with it, although it was previously possible

**To Reproduce**

1. try to create a did:web account
2. reserveSigningKey on bsky.social with your did:web
3. notice how it is hardcoded to return zQ3shXjHeiBuRCKmM36cuYnm7YEMzhGnCmCyW92sRJ9pribSF - that's the old bsky.social key and clearly won't work
4. pick your favorite mushroom, go reserveSigningKey there, note that it seems to work
5. put the favorite mushroom and the corresponding signing key in your did:web
6. createAccount until you get the right mushroom
7. "DID document signing key does not match service signing key"

**Expected behavior**

Of course, it would be optimal to have a documented and not "resend the request until you hit the right mushroom" way of making a did:web account. But at least for now I'd hope the reserved key is used in account creation.

Not sure what exactly is running on the live servers, seems like the entryway-twilio branch is closest to bsky.social as unlike main it does answer to reserveSigningKey with the hardcoded key. If this is the case, passing the did here: https://github.com/bluesky-social/atproto/blob/entryway-twilio/packages/pds/src/api/com/atproto/server/createAccount.ts#L282 could solve this, as each federated pds seems to be running something more similar to main and they do not hardcode reserveSigningKey.

I suppose the entryway reserveSigningKey (or a later equivalent endpoint) could also assign and return a pds, eliminating the need to run createAccount until you get the right one.

**Comment by bnewbold** [comment]
hmm, seems like this broke around the time we set up the entry way. the `reserveSigningKey` mechanism isn't our final plan for account migration, which is related to `did:web` account signup because you are sort of migrating in with an existing DID.

cc: @dholms to confirm, and if there is a current work-around

**Comment by goeo-** [comment]
the new create account path fixes this, closed the issue.

## small tutorial for if anyone finds this and is interested:

if you use an existing did for `com.atproto.server.createAccount` the account it wants bearer authentication with a jwt signed by the did’s signing key (jwt to be formatted like `com.atproto.server.getServiceAuth` output)

once you pass that check and make the account, you can call `com.atproto.identity.getRecommendedDidCredentials`, and take the pds signing key from there (remember to remove did:key:)

after setting that as the signing key you `com.atproto.server.activateAccount` and you’re done

**Comment by goeo-** [comment]
details on signing a jwt, python code taken from @DavidBuchanan314:

```shell
openssl ecparam -name secp256r1 -genkey -noout -out privkey.pem
openssl ec -in privkey.pem -pubout -out pubkey.pem

pip install cryptography==41.0.3 multiformats==0.2.1 multiformats-config==0.2.0.post4
cat <<eof > get_did_key.py
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization
import multiformats

def encode_did_pubkey(pubkey: ec.EllipticCurvePublicKey):
	assert(type(pubkey.curve) is ec.SECP256R1)
	compressed_public_bytes = pubkey.public_bytes(
		serialization.Encoding.X962,
		serialization.PublicFormat.CompressedPoint
	)
	return multiformats.multibase.encode(
		multiformats.multicodec.wrap("p256-pub", compressed_public_bytes),
		"base58btc"
	)

print(encode_did_pubkey(serialization.load_pem_public_key(open("pubkey.pem", "rb").read())))
eof

python get_did_key.py
```

use result as publicKeyMultibase on your did:web, see https://genco.me/.well-known/did.json


base64 urlsafe (rfc 4648 §5):
```
{"iss":"{your did:web}","aud":"{your pds (new) did}","exp":{unix timestamp in seconds, after now}}
```

prepend the result with `eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.`, write this to a file "jwt.txt", make sure there is no newline at the end
```shell
openssl dgst -sha256 -sign privkey.pem -out jwt_signature jwt.txt
(echo -n .; cat jwt_signature | base64 | tr + - | tr / _ | tr -d =) >> jwt.txt
```

jwt.txt will now contain a jwt you can use as a Bearer on createAccount

**Comment by joncar** [comment]
To expand on that, here are the full steps I went through to create my did:web:

```
# This creates an account on pds.example.com, backed by the HTTPS server at did.example.com, using the handle myhandle.xyz. Your did:web and handle can be the same, of course, but for the purpose of writing this I did it as generically as possible.
# Remember that you can never change the did:web's hostname (but you can change the handle) so only do it using a domain you intend to control forever. Boring .com, .net, etc domains are best for this. Avoid using a ccTLD.
# It uses the program from https://github.com/L11R/bsky-did-web/tree/master as a helper to create the did document and key.

# create a temporary key

PRIVKEY=$(./didweb genkey)
PUBKEY=$(echo -n $PRIVKEY | ./didweb pubkey)

# create a did.json file
./didweb gendid --handle myhandle.xyz --pubkey $PUBKEY --hostname pds.example.com > did.json

# -> upload it to https://did.example.com/.well-known/did.json

# createInviteCode

curl   --fail   --silent   --show-error   --request POST   --user "admin:REPLACE_WITH_YOUR_PDS_ADMIN_PASSWORD"   --header "Content-Type: application/json"   --data '{"useCount": 1}'   "https://pds.example.com/xrpc/com.atproto.server.createInviteCode"

# createAccount

TOKEN=$(./didweb sign --privkey $PRIVKEY --iss did:web:did.example.com --aud did:web:pds.example.com --exp 180)

curl --verbose  --fail   --silent   --show-error   --request POST --header "Authorization: Bearer $TOKEN"  --header "Content-Type: application/json"   --data "{\"email\":\"youremail@outlook.com\", \"handle\":\"myhandle.xyz\", \"password\":\"XXX_REPLACE_THIS_XXX\", \"inviteCode\":\"pds-invite-replace-this\"}"   "https://pds.example.com/xrpc/com.atproto.server.createAccount"

TOKEN=accessJwt_value_from_response

# getRecommendedDidCredentials

curl --verbose  --fail   --silent   --show-error   --request GET --header "Authorization: Bearer $TOKEN" https://pds.example.com/xrpc/com.atproto.identity.getRecommendedDidCredentials

# -> edit your did.json to use verificationMethods.atproto (without the did:key prefix)

# activateAccount

curl --verbose  --fail   --silent   --show-error   --request POST --header "Authorization: Bearer $TOKEN" https://pds.example.com/xrpc/com.atproto.server.activateAccount
```

**Comment by katietheqt** [comment]
This issue appears to be present again for the official `bsky.social` PDS - following the steps in the reproduction causes the exact same issue, where brute forcing requests to hit the "correct" PDS causes a `DID document signing key does not match service signing key` error as expected. 

However, attempting to do it the "correct" way by providing an `Authorization` header just causes an `AuthenticationRequired` error with no message, regardless of the validity of the header. This happens both with `did:web` and `did:plc` DIDs. 

When testing against a local PDS, this issue doesn't occur and the account is created fine, so I can only speculate that this is due to code that isn't present in the public repository.

**Comment by goeo-** [comment]
I can confirm that when I said this was fixed, I meant for the code
contained in the repo— what Bluesky PBC runs on the entryway seems to be
different and non open source.

I do think it would be cool if they hosted did:web accounts
