### ISSUE TITLE
Some liked posts aren’t appearing in the Likes feed

### ISSUE THREAD

**Issue by mikeyclarke** [bluesky-social/atproto#2121]
**Describe the bug**

Liked posts are disappearing from my Likes feed.

**Details**

Posts are missing from both the XRPC app.bsky.feed.getActorLikes endpoint and the Bluesky app/website.

**Additional context**

A few days ago all but one of my liked posts disappeared from my Likes feed. I refrained from reporting it then because I’m building a Bluesky client and so it was plausible (though unlikely in the extreme given that I’m only using read API methods at the moment) that I’d somehow unliked the posts through the API.

Today my remaining like also disappeared and I was able to track down the post. The first sceeenshot below shows the post in question in the author’s feed on the Bluesky website. As you can see, it’s still marked as liked. The second screenshot shows my Likes feed on the Bluesky website. As you can see, no posts are listed. I’ve since tracked down another of my missing liked posts and it too is still marked as liked in the author’s feed.

Apologies if this has already been reported, I couldn’t see any similar issues in this repository or the social-app repo.

![IMG_0370](https://github.com/bluesky-social/atproto/assets/2198581/d0255020-2b1b-495f-977c-307e65d78c8e)
![IMG_0372](https://github.com/bluesky-social/atproto/assets/2198581/ebf5673a-8b26-439a-8487-1347fb0edce5)

**Comment by ericvolp12** [comment]
Hey, thanks for this report!

I found the bug in our like paging logic and am deploying a fix right now, should be resolved in a few minutes!

**Comment by ericvolp12** [comment]
Okay after a false start, I think I got this fixed in prod. There was an issue with how we were choosing cursors when paging over likes, thanks for raising this issue and please let me know if it persists!

**Comment by mikeyclarke** [comment]
Yep, my likes have all reappeared now. Thanks for the prompt fix! 🙏
