### ISSUE TITLE
Fix up or remove well-known/did.json endpoint

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#213]
Do we want to be serving a did:web from our server? 

I'm leaning toward no.

Remove if not, or fix up if so.

**Comment by snarfed** [comment]
Funny! Checking https://bsky.app/.well-known/did.json (and https://atproto.com/.well-known/did.json) was one of the first things I did once I got far enough into grokking the specs.

**Comment by dholms** [comment]
Yeah my main issue here is that the did for the server is did:plc not did:web. We don't want to serve it as did:web & I think it breaks the spec to serve did:plc as such 🤔 

We also have an XRPC method - `com.atproto.resolveName` - for resolving the server address to a did doc.

https://github.com/decentralized-identity/.well-known

Adding the did-configuration route for proving ownership of a did could make sense at some point

**Comment by pfrazee** [comment]
@dholms Sorry I should have chimed in sooner.

I do think we want to support did:web now. I think it's useful for self-hosters who understand the tradeoffs they're making, and it gives us backpressure in case did:plc ends up being a mis-step. The cost of support is extremely minor as well.

**Comment by dholms** [comment]
Hmm yeah fair point.

I still don't think we want _every_ PDS serving something off of the did:web endpoint. If a PDS's DID is did:plc, they shouldn't serve that from well-known/did.json since that's misrepresentative.

We'll probably want to toggle the route on & off based on if the server's DID is plc v web

**Comment by pfrazee** [comment]
Yeah this will need to be a configured choice
