### ISSUE TITLE
app.bsky.feed.defs#blockedPost includes wrong post URI

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/atproto#2164]
**Describe the bug**

In the `app.bsky.feed.getPostThread` response, when a blocked post is included on the replies list, it seems to have an incorrect URI field. The URI here is the URI of the root of the thread instead of the blocked post. This used to be the URI of the blocked post before if I remember correctly.

**To Reproduce**

I load the `getPostThread` of this post: https://bsky.app/profile/benejesserit.bsky.social/post/3kkziplpfi227

https://amanita.us-east.host.bsky.network/xrpc/app.bsky.feed.getPostThread?uri=at%3A%2F%2Fdid%3Aplc%3Atfahkkr5sqnhuyf42e7murp5%2Fapp.bsky.feed.post%2F3kkziplpfi227

The response includes a post:

```json
{
    "$type": "app.bsky.feed.defs#blockedPost",
    "uri": "at://did:plc:tfahkkr5sqnhuyf42e7murp5/app.bsky.feed.post/3kkziplpfi227",
    "blocked": true,
    "author": {
        "did": "did:plc:c2bygxhvcruypbofcpmpp3al",
        "viewer": {
            "blockedBy": true
        }
    }
},
```

The URI `at://did:plc:tfahkkr5sqnhuyf42e7murp5/app.bsky.feed.post/3kkziplpfi227` is the URI of the top post whose thread I've loaded, and definitely not a post by `did:plc:c2bygxhvcruypbofcpmpp3al`.

**Expected behavior**

It should be something like `at://did:plc:c2bygxhvcruypbofcpmpp3al/app.bsky.feed.post/...`.

**Comment by mackuba** [comment]
Hmm, looks like this might have been fixed?…

**Comment by devinivy** [comment]
Good call, this should have been resolved with https://github.com/bluesky-social/atproto/pull/2201 👍
