### ISSUE TITLE
Pagination on app.bsky.feed.getPostThread

### ISSUE THREAD

**Issue by lokxii** [bluesky-social/atproto#2351]
Currently there is no pagination on getPostThread. But a community on bsky just created a post with 1060 replies.

Calling getPostThread gives a 2MB json response and setting depth to 1 gives slightly more than 1MB json response. While clients seem to be able to handle this amount of data, is it really not a problem to return this amount of data in single request? I am not a web dev so I'm not sure what is the average response size of a response but I never saw a 2MB json response.

Now the original author of the post is replying to every single comments. I can see the response json will get a lot bigger.

Just curious is this behavior expected?

**Comment by devinivy** [comment]
It's expected and usually not an issue, but also not ideal.  There's a good chance we'll address this when we have an opportunity.  It might require remodeling `feed.getPostThread`, which has some other related limitations too, such as not being able to get posts above a deleted ancestor post.
