### ISSUE TITLE
lex-cli generating [object Promise]

### ISSUE THREAD

**Issue by scarryaa** [bluesky-social/atproto#2371]
**Describe the bug**

When lex-cli is run, it is generating `[object Promise]` instead of the relevant TypeScript code.

**To Reproduce**

1. Install lex-cli globally
2. Run lex-cli on lexicon defs
```node
lex gen-api ./src/client ../../lexicons/com/atproto/*/* ../../lexicons/app/bsky/*/* ../../lexicons/tools/ozone/*/*
```

**Expected behavior**

lex-cli should generate the relevant typescript files, such as
```typescript
export interface StatusAttr {
  applied: boolean
  ref?: string
  [k: string]: unknown
}

export function isStatusAttr(v: unknown): v is StatusAttr {
  return (
    isObj(v) &&
    hasProp(v, '$type') &&
    v.$type === 'com.atproto.admin.defs#statusAttr'
  )
}

export function validateStatusAttr(v: unknown): ValidationResult {
  return lexicons.validate('com.atproto.admin.defs#statusAttr', v)
}
```

**Details**

- Operating system: Windows
- Node version: v20.3.0

**Additional context**

I've also noticed that the tool does not work correctly on Windows (because the glob pattern is not supported? But I am also geting the [object Promise] behavior in bash).

Apologies if this is just user error, but I can't seem to figure out the issue.

**Comment by scarryaa** [comment]
After doing some digging, It looks like the issue is with `prettier.format(...)`
```typescript
content: `${banner()}${prettier.format(src, PRETTIER_OPTS)}`,
```

If I change it to 
```typescript
content: `${banner()}${await prettier.format(src, PRETTIER_OPTS)}`,
```
it works correctly.

**Comment by mary-ext** [comment]
should be fixed by https://github.com/bluesky-social/atproto/commit/b8f8f06a12c88b12f4c7eb7316e30d02c6b4d399

**Comment by pdandradeb** [comment]
were you able to try this? facing the same issue here with up to date main.
