### ISSUE TITLE
support relay pagination

### ISSUE THREAD

**Issue by mikestaub** [bluesky-social/atproto#252]
I noticed here that pagination parameters are being included.

https://atproto.com/lexicons/bsky-app#appbskygetnotifications

If a client wants to implement infinite scrolling UI, relay based is easier to work with. Should this method be augmented to support both or should a new method ( ie `app.bsky.getNotificationsRelay` ) be created?

**Comment by pfrazee** [comment]
The lexicon docs were a tad outdated so I just pushed the latest.

To answer your question, we include a `cursor` field on the individual records that are emitted from any pagination-based method. It's that value that you'll pass into a pagination parameter like `before`

**Comment by devinivy** [comment]
I think this is now addressed, but if there are more thoughts or questions feel free to chime in 👍
