### ISSUE TITLE
Shreyan's posts from before his PDS migration disappeared from my home timeline

### ISSUE THREAD

**Issue by mackuba** [bluesky-social/atproto#2537]
**Describe the bug**

I've been playing with the timeline API, and I've noticed that all posts from @ShreyanJain9 before May 25 seem to have disappeared from my "following" timeline. If I scroll a few days down, I only occasionally see them if there's a reply from myself below (so it's really the reply that's being shown, and the post is just shown as a parent). I don't see any other posts from him, only from everyone else (and it looks the same in the API).

This seems to more or less coincide with when he mentioned he started working on migrating the account to his PDS…

**To Reproduce**

Well you can't reproduce it since it's my timeline… Here's how it looks for me in the API called from a Ruby console (using Minisky gem):

```rb
params = { limit: 100 }
30.times do |i|
  result = sky.get_request('app.bsky.feed.getTimeline', params)
  params[:cursor] = result['cursor']
  last_post = result['feed'][-1]
  last_date = last_post['reason'] ? last_post['reason']['indexedAt'] : last_post['post']['indexedAt']
  shreyan = result['feed'].select { |x| x['post']['author']['handle'] == 'shreyanjain.net' }
  puts "Loaded #{result['feed'].length} posts until #{last_date}... Shreyan -> #{shreyan.length}"
end
```

Result:

```
Loaded 99 posts until 2024-05-30T21:08:32.000Z... Shreyan -> 20
Loaded 97 posts until 2024-05-30T15:01:21.942Z... Shreyan -> 4
Loaded 98 posts until 2024-05-30T01:21:54.000Z... Shreyan -> 31
Loaded 99 posts until 2024-05-29T16:28:52.154Z... Shreyan -> 9
Loaded 97 posts until 2024-05-29T03:52:14.722Z... Shreyan -> 13
Loaded 98 posts until 2024-05-28T16:13:26.572Z... Shreyan -> 22
Loaded 98 posts until 2024-05-27T19:54:05.672Z... Shreyan -> 13
Loaded 95 posts until 2024-05-27T14:58:10.107Z... Shreyan -> 27
Loaded 96 posts until 2024-05-26T20:46:59.633Z... Shreyan -> 26
Loaded 89 posts until 2024-05-26T17:06:42.167Z... Shreyan -> 32
Loaded 79 posts until 2024-05-26T01:15:31.535Z... Shreyan -> 40
Loaded 77 posts until 2024-05-25T22:50:41.947Z... Shreyan -> 33
Loaded 96 posts until 2024-05-25T17:59:27.834Z... Shreyan -> 40
Loaded 95 posts until 2024-05-24T22:57:52.599Z... Shreyan -> 0
Loaded 95 posts until 2024-05-24T11:28:25.672Z... Shreyan -> 0
Loaded 99 posts until 2024-05-24T01:19:22.280Z... Shreyan -> 0
Loaded 99 posts until 2024-05-23T17:49:58.278Z... Shreyan -> 0
Loaded 94 posts until 2024-05-23T07:25:42.959Z... Shreyan -> 0
Loaded 95 posts until 2024-05-22T22:27:51.976Z... Shreyan -> 0
Loaded 96 posts until 2024-05-22T19:12:47.496Z... Shreyan -> 0
Loaded 97 posts until 2024-05-22T12:07:10.856Z... Shreyan -> 0
Loaded 95 posts until 2024-05-21T23:29:00.000Z... Shreyan -> 0
Loaded 100 posts until 2024-05-21T18:20:11.395Z... Shreyan -> 0
Loaded 96 posts until 2024-05-21T01:46:48.247Z... Shreyan -> 0
Loaded 97 posts until 2024-05-20T16:41:38.006Z... Shreyan -> 0
Loaded 97 posts until 2024-05-19T16:25:56.556Z... Shreyan -> 0
Loaded 99 posts until 2024-05-18T20:48:33.803Z... Shreyan -> 0
Loaded 98 posts until 2024-05-17T21:38:46.932Z... Shreyan -> 0
Loaded 95 posts until 2024-05-17T09:21:24.485Z... Shreyan -> 0
Loaded 98 posts until 2024-05-16T18:18:59.952Z... Shreyan -> 0
```

**Comment by ericvolp12** [comment]
That seems kinda strange, during a PDS migration we don't do anything to someone's timeline unless they tombstone their repo and even then we will mark the posts as deleted but won't delete them from people's timelines since they won't hydrate and eventually fall out of the lookback window.

TBH this is something that seems to have solved itself mostly, timelines only go back ~5,000 items on average so eventually your TL will be full of Shreyan again.

**Comment by ShreyanJain9** [comment]
> timelines only go back ~5,000 items on average so eventually your TL will be full of Shreyan again.

Crazy way to call me terminally online 🙄

**Comment by ShreyanJain9** [comment]
> @ShreyanJain9 did you do anything non-standard there by any chance that could have caused this?

Don't think so!

**Comment by mackuba** [comment]
Closing, my timeline is indeed full of Shreyan again 😎
