### ISSUE TITLE
Update a profile via api

### ISSUE THREAD

**Issue by Kadmas** [bluesky-social/atproto#2583]
**Is your feature request related to a problem? Please describe.**

I was looking through the api documentation for the ability to update the profile. In particular for the avatar and the banner. I'm not having luck finding this.

**Describe the solution you'd like**

An answer if this is planned for the future

**Describe alternatives you've considered**

🤷 

**Additional context**

**Comment by bnewbold** [comment]
We have a tutorial about this here: https://docs.bsky.app/docs/tutorials/editing-profiles

Profiles, like posts, are "records". Creating and updating them is done by creating or updating the relevant records.

**Comment by Kadmas** [comment]
Thank you @bnewbold. This didn't immediately jump out at me when skimming the api docs. If anyone else finds this issue and is looking for the api call info it's [here](https://docs.bsky.app/docs/api/com-atproto-repo-put-record)

**Comment by Kadmas** [comment]
Closing as completed. Thanks again
