### ISSUE TITLE
`app.bsky.graph.unmuteThread` not working

### ISSUE THREAD

**Issue by mimonelu** [bluesky-social/atproto#2585]
**Describe the bug**

`viewer.threadMuted` in root post remains true after calling `app.bsky.graph.unmuteThread`

**To Reproduce**

1. Call `app.bsky.graph.muteThread` with root post uri
2. Check `viewer.threadMuted` is `true` (this is correct)
3. Call `app.bsky.graph.unmuteThread` with same root post uri 
4. Check `viewer.threadMuted` is `true` (this is wrong)

**Expected behavior**

`viewer.threadMuted` in root post should be `false`

**Details**

- Operating system: Mac OS 14.5
- Node version: v18.17.1

**Comment by dholms** [comment]
Thanks for the report. Out of curiosity, were you testing this yesterday? I believe I got in a bugfix for this issue, but there may be some funky state lurking around if you were messing with this before the fix got in

**Comment by mimonelu** [comment]
@dholms 
Yes, I tested it yesterday. However, the results did not change when tested now.
One point, I forgot to mention is that I'm actually using BskyAgent.app.bsky.graph.unmuteThread({ root }), so maybe BskyAgent is the cause.

**Comment by mimonelu** [comment]
The problem seems to be solved, thanks.
