### ISSUE TITLE
OAuth provider: yet more client-metadata error descriptions

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/atproto#2719]
We mostly have good error messages for client-metadata fetch problems, but I think there are a couple paths that result in a generic "Invalid client configuration" message, which is hard for client devs to debug.

Some specific cases I suspect (not confirmed) result in this error:

- problems parsing JWKs (https://github.com/bluesky-social/atproto/issues/2718)
- SSRF fetch issues (aka, URL is on a private IP range)

IIRC, there is also a situation where we wrap other errors with the specific client-metadata error, and that doesn't result in a specific message (?).

**Comment by PIPOGit** [comment]
Hi!

I'm performing some tests from "localhost", using this "client_id": [https://bluesky.scienceontheweb.net/oauth/client-metadata.json](https://bluesky.scienceontheweb.net/oauth/client-metadata.json)y. The content is as follows:
```json
{
	"client_id": "https://bluesky.scienceontheweb.net/oauth/client-metadata.json",
	"application_type": "web",
	"client_name": "BlueSky OAuth2 Example",
	"client_uri": "https://bluesky.scienceontheweb.net",
	"dpop_bound_access_tokens": true,
	"grant_types": [
		"authorization_code",
		"refresh_token"
	],
	"redirect_uris": [
		"https://bluesky.scienceontheweb.net/oauth/callback.php"
	],
	"response_types": [
		"code"
	],
	"scope": "atproto transition:generic",
	"token_endpoint_auth_method": "none"
}
```

I'm following the specs [here](https://docs.bsky.app/docs/advanced-guides/oauth-client#client-and-server-metadata) and [here](https://github.com/bluesky-social/proposals/blob/main/0004-oauth/README.md).

These are the headers:
```json
{
    "Host":  "bsky.social",
    "Accept":  "*/*",
    "Content-Type":  "application/x-www-form-urlencoded"
}
```

and this the request body:
```json
{
    "login_hint":  "did:plc:yhtmtr4drtu3rsgauj3etua6",
    "redirect_uri":  "https://bluesky.scienceontheweb.net/oauth/callback.php",
    "state":  "af8c1d17-1884-4518-b2f3-d580d621da4b",
    "code_challenge_method":  "S256",
    "client_id":  "https://bluesky.scienceontheweb.net/oauth/client-metadata.json",
    "response_type":  "code",
    "scope":  "atproto",
    "code_challenge":  "Webc9WAz-mMgRm2IyNJMu0PHWvDDdSdcydjjHpY-izo"
}
```

The server's response is: **400**:
```json
{
	"error": "invalid_client_metadata",
	"error_description": "Invalid client configuration"
}
```

Can somebody tell me what is wrong with the configuration file, please?

Many thanks in advance. ;^)

**Comment by matthieusieben** [comment]
Hey @PIPOGit, it looks like the SSL certificate on your domain might be the issue here:
<img width="959" alt="Capture d’écran 2024-09-16 à 19 38 39" src="https://github.com/user-attachments/assets/918e9a7c-57bb-4cfc-818f-f3cf6ef067fe">

I will look into getting better feedback in that particular case.

**Comment by PIPOGit** [comment]
Oh, ok!

That should be the issue.

It's a "virtual domain" in AwardSpace, so don't look any further... Unless You accept this "fuzzy" certs. 😉

Thanks!

**Comment by matthieusieben** [comment]
This [PR](https://github.com/bluesky-social/atproto/pull/2755) will return more comprehensible error messages including in this particular case.

**Comment by matthieusieben** [comment]
https://github.com/bluesky-social/atproto/pull/2755 was deployed. Please re-open a new issue if the error are still too vague.

**Comment by PIPOGit** [comment]
> How can i get my client-metadata.json ? I want to post on the behalf of a user after fetching the access token based on the credentials i will get from user and then refresh the token as well.

Just, take a look [**here**](https://docs.bsky.app/docs/advanced-guides/oauth-client#client-and-server-metadata)
