### ISSUE TITLE
Problem to list convo and send message

### ISSUE THREAD

**Issue by Cristuker** [bluesky-social/atproto#2775]
**Describe the bug**

Well Im trying to create a bot who send message on DM to save posts. I tried using HTTP request like the below code and I receive 404 always following the [doc](https://docs.bsky.app/docs/api/chat-bsky-convo-get-convo-for-members) and also I tried using the package for typescript but I received this error [XRPCError: XRPC Not Supported #1954
](https://github.com/bluesky-social/atproto/issues/1954) but this solution don't work for me.

**To Reproduce**

1. Create a node.js project
2. add the following code

``` 
 const config = {
    method: "get",
    maxBodyLength: Infinity,
    url: `https://public.api.bsky.app/xrpc/chat.bsky.convo.getConvoForMembers?members=${did}`,
    headers: {
      Accept: "application/json",
      Authorization: `Bearer ${token}`,
    },
  };

  const response = await axios(config);
  console.log(JSON.stringify(response.data));
  return { data: response.data };
```

the other approach

```

  await agent.login({
    identifier: ultraConfidentialUser,
    password: ultraConfidentialPassword
  })
  const res = await agent.chat.bsky.convo.getConvoForMembers({
    members: [did]
  })
  console.log(res)

```

**Expected behavior**

list convos for the did that I send
**Details**

- Operating system: linux
- Node version: 18

**Comment by eduwr** [comment]
I was having the same issue.

the problem is that you need to use [service proxy ](https://atproto.com/specs/xrpc#service-proxying) to forward the request to the chat service. To do this, you need to add the following header:

```txt
      "Atproto-Proxy": "did:web:api.bsky.chat#bsky_chat",
```

However, in order to use the service proxy, you cannot send the request to the [PDS Entryway service](https://docs.bsky.app/docs/advanced-guides/entryway#virtual-pds) (i.e. `https://bsky.social`). Instead, you must send the request to your own PDS, which acts as the home for your account. You can obtain the PDS when you create your account or by creating a session.


Here is my implementation:

```ts
import axios from "axios";

const SOCIAL_BASE_URL = "https://bsky.social/xrpc";
export const blueSkySocialAPI = axios.create({ baseURL: SOCIAL_BASE_URL });

export type Session = {
  did: string;
  accessJwt: string;
  refreshJwt: string;
  service: {
    id: string;
    type: string;
    serviceEndpoint: string;
  }[];
};

export const createSession = async (): Promise<Session> => {
  const { data } = await blueSkySocialAPI.post(
    "com.atproto.server.createSession",
    {
      identifier: process.env.BLUESKY_USERNAME,
      password: process.env.BLUESKY_APP_PASSWORD,
    },
    {
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
    },
  );

  blueSkySocialAPI.defaults.headers.common["Authorization"] =
    `Bearer ${data.accessJwt}`;

  return {
    did: data.did,
    accessJwt: data.accessJwt,
    refreshJwt: data.refreshJwt,
    service: data.didDoc.service,
  };
};

export const listConvos = async (accountPDS: string) => {
  const url = "chat.bsky.convo.listConvos";

  const resp = await blueSkySocialAPI.get(url, {
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      "Atproto-Proxy": "did:web:api.bsky.chat#bsky_chat",
    },
    baseURL: `${accountPDS}/xrpc`,
  });
  console.log("res ", resp);
  return resp.data;
};

const session = await createSession();
const convos = await listConvos(session.service[0].serviceEndpoint);
console.log(convos);
```

**Comment by Cristuker** [comment]
I'm sorry but my implementation was wrong

**Comment by Lermatroid** [comment]
@Cristuker how was your implementation wrong? I am running into a similar issue.

**Comment by Cristuker** [comment]
@Lermatroid I don't remember exactly what I refactored, but this is the link to the file. I did many refactors after this post but if you search into the commits it can help you https://github.com/Cristuker/save-to-later/blob/main/src/sendMessage.ts

**Comment by NISHIMURA-MieMatsusaka-Kazunari** [comment]
You must access the service endpoint, not “https://bsky.social”.
The service endpoint is returned by didDoc in the “com.atproto.server.getSession” response.

**Response Example**
```
{
	"handle":"sarudoko.net",
	"did":"did:plc:gvkzjuwkdf6a2ztjcfsovn65",
	"didDoc":{
		"@context":[
		"https://www.w3.org/ns/did/v1",
		"https://w3id.org/security/multikey/v1",
		"https://w3id.org/security/suites/secp256k1-2019/v1"
		],
		"id":"did:plc:gvkzjuwkdf6a2ztjcfsovn65",
		"alsoKnownAs":["at://sarudoko.net"],
		"verificationMethod":[
		{
			"id":"did:plc:gvkzjuwkdf6a2ztjcfsovn65#atproto",
			"type":"Multikey",
			"controller":"did:plc:gvkzjuwkdf6a2ztjcfsovn65",
			"publicKeyMultibase":"zQ3shcu7qrqCcKjPB81HkWbPRtU8YaZNWCcNxLg2H7woYL4s3"
		}
		],
		"service":[
		{
			"id":"#atproto_pds",
			"type":"AtprotoPersonalDataServer",
			"serviceEndpoint":"https://scarletina.us-east.host.bsky.network"
		}
		]
	},
	"email":"support@sk.sarudoko.net",
	"emailConfirmed":true,
	"emailAuthFactor":false,
	"active":true
}
```
