### ISSUE TITLE
Firehose consumers do not receive root block in case of too big seq commit

### ISSUE THREAD

**Issue by MarshalX** [bluesky-social/atproto#2893]
**Describe the bug**

Firehose consumers do not receive root block in case of too big seq commit. 

**To Reproduce**

I wrote a corresponding unit test in the linked PR that reproduces the issue

**Actual behavior**

`car.blocks` are always empty 

**Expected behavior**

`car.blocks` must be always one (the root one)

**Additional context**

Line no. 29 is so suspicious:
https://github.com/bluesky-social/atproto/blob/81ae1b12389f1c2b1ca9aa5ed0660a0f569c4c9d/packages/pds/src/sequencer/events.ts#L25-L31

Here is why:
- `.add` of `BlockMap` returns a promise and no one waits for resolve (forgotten `await`)
- input arg of `.add` is typed as`LexValue` which goes through `dataToCborBlock(lexToIpld(value))`. That does not make sense since we just move the block from one `BlockMap` to another one. `newBlocks.get` returns bytes already.

P.S. I dug into this because I got reports from my lovely Python devs that `commit.blocks` received from the firehose message frame could be missed. But it is marked as a required field in the lexicon. From our observation, it is missed always in combination with `tooBig=true`. I will continue my journey, but if you have any ideas I would appreciate it

**Comment by MarshalX** [comment]
Hi @dholms! I am pinging you here since you are the last one in the git blame for this file :)

**Comment by MarshalX** [comment]
bump :(

**Comment by bnewbold** [comment]
The intention going forward is that the commit block should be included as the root block. It is also possible it isn't getting passed through the relay? We'll need to investigate.

**Comment by dholms** [comment]
Hey @MarshalX thanks for flagging this!

I put up a fix for the PDS codebase (https://github.com/bluesky-social/atproto/pull/2923). But we seldom if ever output tooBig events on the PDS. I'll flag this in the relay codebase which I think is likely the culprit of these missing commits

**Comment by dholms** [comment]
Oh rip I didn't see your PR on this 😅

Let me take a closer look, I might prefer yours
