### ISSUE TITLE
PLC docs: signing, hashing, crypto details

### ISSUE THREAD

**Issue by bnewbold** [bluesky-social/atproto#295]
The current DID Placeholder (`did:plc`) docs mention signing and hashing, but don't describe how things should be encoded so that they can be signed or hashed.

From poking through the code, it looks like operation signing is done by creating "unsigned" object schemas which don't include the `sig` field, then encoding with IPLD DAG-CBOR (resulting in a byte array), signing those bytes (resulting in bytes), then encoding the signature as base64url.

Unless i'm not seeing it, the current docs don't mention that when updating a signing key using a signing key, it is the *previous* signing key that should be used to sign, not the new key. The new signing key would be used for all future signatures (except any recovery operation).

To generate the PLC code itself, the signed creation operation is encoded with IPLD DAG-CBOR (resulting in a byte array), then those bytes are hashed as described in the existing docs (aka, SHA-256, encoded with base32, truncated to 24 characters, then prefixed with `did:plc:`).

Separately, I noticed when reading the current implementation that the same signing key is used for all accounts on the placeholder server. I had assumed that each user would have a distinct keypair, but I guess it doesn't really matter.

**Comment by dholms** [comment]
Yup you got that right all correct. 

Agreed that we should make this all more explicit in the PLC docs. 

Current supported keys are secp256k1 & NIST P256 (secp256r1). I would like to add ed25519 to this as well.

The server does use just a single signing key for all users. Storing keys securely (in for instance, a cloud HSM) can be expensive ($1/mo/key in AWS KMS). Not bad for one key, but gets very expensive if you have a key per user. So having only one key that requires good op sec actually improves security for the server.

**Comment by dholms** [comment]
Recovery keys can either be held by the server or supplied by the user

**Comment by AaronGoldman** [comment]
This may end up replaced with

CBOR Object Signing and Encryption (COSE)
https://datatracker.ietf.org/doc/html/rfc8152

If it looks like the IPFS ecosystem is standardizing on JOSE/COSE for object signing.

**Comment by AaronGoldman** [comment]
```
const documentData = z.object({
  did: z.string(),
  signingKey: z.string(),
  recoveryKey: z.string(),
  username: z.string(),
  atpPds: z.string(),
})
```

One could certainly imagine adding a 
```
plcKey: z.string(),
```
To the DID Document if the user wanted to use some other services to order the document updates they would be responsible for getting the deltas signed and then uploading them to the PLC server. 

But at this time it is simpler to just assume everyone is trusting the PLC server to keep the Document deltas ACID

**Comment by bnewbold** [comment]
docs now exist in the README for https://github.com/bluesky-social/did-method-plc
