### ISSUE TITLE
Consider a nonce in actor declaration

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#298]
It would be good for each declaration CID to be unique so devs can't shortcut the process of linking to declaration - which would be prone to footguns.

Optionally, the "nonce" could just be the did of the repo.

**Comment by pfrazee** [comment]
> Optionally, the "nonce" could just be the did of the repo.

Hmm. Is there any world in which we'd regret that? Like eg, it turns out DIDs dont work how we want, we fall back to did:web and redirects, and now we're hosed?

I'm inclined to do that though

**Comment by dholms** [comment]
If your did changes you're already breaking all follows (since they reference DID as well). 

So I _think_ it's okay.

Alternately, our nonce could just be the `createdAt` time 🤷‍♂️

**Comment by dholms** [comment]
We don't actually need these to be _unique_ we just want to prevent like 2 or 3 globally understood CIDs that represent each actor type

**Comment by pfrazee** [comment]
> If your did changes you're already breaking all follows (since they reference DID as well).

Fair point. Okay then I like using the did. It's kind of handy to have in there anyway.

**Comment by dholms** [comment]
removed declarations
