### ISSUE TITLE
Bluesky Invalid Handle

### ISSUE THREAD

**Issue by codenoid** [bluesky-social/atproto#3004]
I don't know why but the profile returns invalid handle

Link: https://bsky.app/profile/sveltejs.bsky.social

<img width="306" alt="image" src="https://github.com/user-attachments/assets/cb809412-5525-4c8b-aa33-e987bcf066cc">

**Comment by Cloudhunter** [comment]
Known. Temporary issue caused by the earlier outage.

https://bsky.app/profile/samuel.bsky.team/post/3lavyvkd2622h

They should "come back soon".
