### ISSUE TITLE
[oauth-client-browser] 400 from /oauth/par request: Authorization server requires nonce in DPoP proof

### ISSUE THREAD

**Issue by potterbm** [bluesky-social/atproto#3078]
When using `@atproto/oauth-client-browser` with the default setup described in [the readme](https://github.com/bluesky-social/atproto/tree/main/packages/oauth/oauth-client-browser), the `/oauth/par` request fails with:
```json
{
    "error": "use_dpop_nonce",
    "error_description": "Authorization server requires nonce in DPoP proof"
}
```

### To Reproduce

1. Create a new `BrowserOauthClient` object ([example](https://github.com/potterbm/bluesky-search-to-block/blob/cb0177a5ecdb2754a3536b768568a2015ed92b88/src/providers/AuthProvider/index.tsx#L19-L33))
2. call `client.init()`
3. call `client.signIn` with a bluesky username
```ts
client.signIn('bryan.town', {
        state: '',
        prompt: 'none', // Attempt to sign in without user interaction (SSO)
        ui_locales: 'en', // Only supported by some OAuth servers (requires OpenID Connect support + i18n support)
}
```

Example app with this behavior: https://search-to-block.bryan.town ([code](https://github.com/potterbm/bluesky-search-to-block))

### Expected behavior

I expected the oauth process to succeed and redirect to my app with a one-time code (and I expected `client.init()` to exchange that for an auth token)

### Details

- Operating system: Mac Sonoma 14.5
- Node version: Vite app built with node v22.11.0
- package version: 1.0.6 (latest at the time of writing)

### Additional Context

Here is the full PAR request:
```
POST https://bsky.social/oauth/par
Headers:
  dpop: eyJhbGciOiJFUzI1NiIsInR5cCI6ImRwb3Arand0IiwiandrIjp7Imt0eSI6IkVDIiwiY3J2IjoiUC0yNTYiLCJ4IjoiTW9IaHhjdG5iYS1aZ1dwbURMMVJDbGlPUHk5Qlk0OUEzSWxPQ213cGRlWSIsInkiOiJCeEg1YWUzREZ4cmk1c29xb21MU3U4RmhyNW1CWkZScVROM3JPV0RFZ1E0In0sImtpZCI6ImNiNDIzZWNmLWM4N2ItNDQwNy1hZTk4LThkNTlhYzBjMDg5ZCJ9.eyJpc3MiOiJodHRwczovL3NlYXJjaC10by1ibG9jay5icnlhbi50b3duL29hdXRoL2NsaWVudC1tZXRhZGF0YS5qc29uIiwiaWF0IjoxNzMyMzE2ODUyLCJqdGkiOiJ1Z2cyNDhvOGJoaiIsImh0bSI6IlBPU1QiLCJodHUiOiJodHRwczovL2Jza3kuc29jaWFsL29hdXRoL3BhciJ9.KrENfrDiUcultC3KKESx8rUxu47QBzHsnZmw2Y5z12jD1_mrOybPPogXAinNKHXl-EvsGnpHmiloLqK7JlESVg



Body: {
    "state": "KDu_qR3M_3CBKRuvkHRtzA",
    "prompt": "none",
    "ui_locales": "en",
    "client_id": "https://search-to-block.bryan.town/oauth/client-metadata.json",
    "redirect_uri": "https://search-to-block.bryan.town",
    "code_challenge": "N1QPLzCDiuR72VsLWY_PqFfQCxm9dbmu8d_-ymQmbvE",
    "code_challenge_method": "S256",
    "login_hint": "bryan.town",
    "response_mode": "fragment",
    "response_type": "code",
    "scope": "atproto"
}
```

Here is the response:
```
400 Bad Request
Headers:
  content-encoding: br
  content-type:  application/json
  access-control-expose-headers: DPoP-Nonce
  dpop-nonce: muM5wVa5OP7EtpBCcNhQydJrFjOuTuBGtMHOuijqJmI
Body: {
    "error": "use_dpop_nonce",
    "error_description": "Authorization server requires nonce in DPoP proof"
}
```

**Comment by Gregoor** [comment]
I'm seeing the issue too! In my case it only occurs once I add "transition:generic" to scope, it goes through fine without it.

**Comment by brianreumere** [comment]
I forget exactly where I read it (it actually might be in the response from `/oauth/par`, which includes an error description `Public clients are not allowed to use silent-sign-on`), but I don't think you can use `prompt: 'none'` in this case. I see the same behavior if I include `prompt: 'none'` in my `signIn()` call, but if I remove it it works (I initially get a `400` because `prompt: 'none'` is included as a request header, but it retries without `prompt: 'none'` and succeeds and redirects to the "An application on your device is asking for permission..." authorization screen.

**Comment by potterbm** [comment]
Thanks everyone for chiming in on this!

I finally got around to trying these solutions, and removing `transition:generic` from the scope did not work, but changing `prompt: 'none'` to `prompt: 'login'` succeeded. I see the same behavior @brianreumere described: the `/oauth/par` fails initially and then retries and successfully redirects to the authorization screen, which results in a successful auth flow.

I appreciate all the help!

**Comment by potterbm** [comment]
I made a docs PR to smooth out these issues for future devs: https://github.com/bluesky-social/atproto/pull/3080

**Comment by potterbm** [comment]
I'm not sure if they will ever get to my PR, however, so I'm going to close this issue manually
