### ISSUE TITLE
Lexicon type: schema fragments

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#314]
We need a simple way to share "libraries" of schema definitions across multiple schemas. This is particularly important for strictly typed languages like Go.

Lexicon needs a new type for storing these definitions to be reused.

**Comment by snarfed** [comment]
Does this need to be a first class type? Could conventions around either files or NSID subdomains do enough of this for a first pass?

**Comment by pfrazee** [comment]
Ah, mercifully it does not! We found a solution to this in the recent rewrite of Lexicon. Essentially a lexicon doc is like a `d.ts`, and like a d.ts it can export many types (eg object definitions). This is now resolved!
