### ISSUE TITLE
"Bad token scope" while using OAuth access token

### ISSUE THREAD

**Issue by nbartels** [bluesky-social/atproto#3186]
**Describe the bug**

First the steps that are working:
If I use handle and app password go to createSession and fetch access token and refresh token this way, I am able to publish a new text post. So the basic publishing code is working. The POST request uses "Authorization: Bearer <access token>" for this.

Now, we implemented the OAuth flow and are able to get an access token. We use the scopes "atproto", "transition:generic" and "transition:chat.bsky". The created access token comes with theses scopes and it looks fine so far.

As soon as I use this access token in the code above and replace the access token from createSession with the token from the oauth flow, the publishing code is not working anymore with the http error code 400 and InvalidToken (bad token scope). 

**To Reproduce**

1. fetch access token using the oauth flow with scope "atproto transition:generic transition:chat.bsky"
2. Try publish (for example) a text post using com.atproto.repo.createRecord

**Expected behavior**

Post is published with HTTP Code 200.

**Additional context**
I already tried to use instead of "Authorization: Bearer <access token>" the "Authorization: DPoP <access token>" with the suitable DPoP http header field. Then I receive another HTTP 400 error. This kind of request should made against the PDS and I use https://bsky.social as server.

Overall the question is. Do I use the access token as it is Meant to be used, is this a bug or should we switch to handle and app password logins?

**Comment by nbartels** [comment]
Problem solved. I have to work with the PDS instance itself and do some dpop magic. The Python example was very helpful reimplementing this in Java ...

**Comment by linhhdinh** [comment]
I am having the same issue. @nbartels  Could you please show the code or docs that resolved it?
