### ISSUE TITLE
Unable to use OAuth - Unexpected server error - client_assertion_type required for "private_key_jwt"

### ISSUE THREAD

**Issue by MarcFletcher** [bluesky-social/atproto#3228]
Thank-you for the library and apologies in advance if this is the wrong place to ask. I am attempting to migrate the logic of this SDK into Java. I've simplified the reproduction using curl.

If anyone can highlight where I am going wrong to generate this error that would be appreciated.

**Describe the bug**

When attempting to make a PAR request for a confidential web OAuth client I'm receiving an unexpected error :

> client_assertion_type required for "private_key_jwt"

Although this is the very first parameter I am providing in the request.

**To Reproduce**

```
curl --location 'https://bsky.social/oauth/par' \
--header 'Accept: application/json' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer' \
--data-urlencode 'client_assertion=[signed_JWT_assertion]' \
--data-urlencode 'client_id=https://myapi.com/bluesky/client-metadata.json' \
--data-urlencode 'redirect_uri=https://myapi.com/v3/social/api/connect/redirect' \
--data-urlencode 'response_type=code' \
--data-urlencode 'scope=atproto transition:generic' \
--data-urlencode 'code_challenge=MqQ20leWJI2CClySgAT5_oZ1GyFjsCfywr35F6AIjt4' \
--data-urlencode 'code_challenge_method=S256' \
--data-urlencode 'state=12345'
```

client-metadata.json

```
{
    "client_id": "https://myapi.com/bluesky/client-metadata.json",
    "application_type": "web",
    "redirect_uris": [
        "https://myapi.com/v3/social/api/connect/redirect"
    ],
    "response_types": [
        "code"
    ],
    "grant_types": [
        "authorization_code",
        "refresh_token"
    ],
    "scope": "atproto transition:generic",
    "token_endpoint_auth_method": "private_key_jwt",
    "token_endpoint_auth_signing_alg": "ES256",
    "dpop_bound_access_tokens": true,
    "jwks": {
        "keys": [
            {
                "crv": "P-256",
                "x": "[val1]",
                "y": "[val2]",
                "kid": "v1",
                "kty": "EC",
                "use": "sig"
            }
        ]
    }
}
```

**Expected behavior**

The PAR response containing the desired request_URI.

**Details**

NA

**Comment by MarcFletcher** [comment]
Walking through the server logic at https://github.com/bluesky-social/atproto/blob/9fd65ba0fa4caca59fd0e6156145e4c2618e3a95/packages/oauth/oauth-provider/src/oauth-provider.ts#L1189 it's not clear to me why I'm running into this error.

**Comment by Makeshift** [comment]
Just in case my reply in Slack gets eaten...

This is happening because Zod is parsing your input payload as a `oauthClientCredentialsNoneSchema`, meaning that the client_assertion_type is being stripped when the `oauthClientCredentialsSchema` validation function is being ran, due to it falling back as part of a zod union. 

Later down the line it tries to validate again, inputting the stripped object, which throws that error.

You need it to parse as a [`oauthClientCredentialsJwtBearerSchema`](https://github.com/bluesky-social/atproto/blob/main/packages/oauth/oauth-types/src/oauth-client-credentials.ts#L7), which requires `client_assertion` to match the schema. 

`aa:bb:cc` matches the schema and allows it to get a bit further, but I'm not familiar enough with JWT to know what it's actually meant to be set to. There's a comment describing it in my link above.

**Comment by MarcFletcher** [comment]
Many thanks for the reply. 

I hadn't mentioned this explicitly but the change from the full `client_assertion` jwt to the empty string `[signed_JWT_assertion]` was just a simplification I made in this issue while trying to reduce the complexity of the problem. I didn't observe a different in the error message given the fully signed jwt, of schema `aa:bb:cc` OR the empty string so I reported using the later.

**Comment by Makeshift** [comment]
Given the curl you posted in slack (with `client_assertion` set to `nothing`) I get the same error as you:
```
{"error":"invalid_request","error_description":"client_assertion_type required for \"private_key_jwt\""}
```

However if I modify `client_assertion` to `aa:bb:cc`, I get:
```
{"error":"invalid_client","error_description":"Validation of \"client_assertion\" failed: JWS Protected Header is invalid"}
```

If you're getting the former error with a `client_assertion` that should be valid, could you PM me it? As part of debugging this, I set up a local development stack, so I can use the debugger to check that your request is being matched as a `oauthClientCredentialsJwtBearerSchema` by the zod union.

**Comment by MarcFletcher** [comment]
The eventual solution for this turned out to be correcting the encoding of the JWT.

The client assertion JWT was not being encoded in a URL safe way, and changing the library being used to generate it allowed the PAR request to be generated as expected. 

The reason bluesky returned a non relevant error is that an earlier 'type parsing process' (server side) was returning a different request object (due to it not recognising the JWT), as described by @Makeshift.

Important Note - DPoP JWTs (incorrectly) encoded are accepted which prevented this issue from being recognised earlier.
