### ISSUE TITLE
Ambiguous timestamp pagination in pds

### ISSUE THREAD

**Issue by devinivy** [bluesky-social/atproto#344]
There are a few views that paginate by timestamp, causing intermittent failing tests.  The issue is that items with the same timestamp may not appear in a consistent order.

This can be fixed by ordering by some identifier after ordering by timestamp, similar to the actor search views: https://github.com/bluesky-social/atproto/blob/0d98291c42dbbd77482b71e7aca47cc3af4ea463/packages/pds/src/api/app/bsky/util/search.ts#L161-L165

Referenced in a `@TODO` here: https://github.com/bluesky-social/atproto/blob/5b4e2b9ee33e43fbbe72a80e97d18310fd9fd248/packages/pds/tests/views/notifications.test.ts#L73-L75

**Comment by dholms** [comment]
Fixed by: https://github.com/bluesky-social/atproto/pull/365
