### ISSUE TITLE
Mentions aren't delivering notifications

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#369]
I've noticed this a couple times, as have users, but haven't dug into tests or anything to confirm it's a backend issue.

**Comment by dholms** [comment]
I haven't done a deep dive on this or anything, but a look at the code suggests it's working correctly & the tests for notifications bear that out as well.

This does however require that the value is the user's did (with no at:// prefix). We can make the intake a little more flexible here, but any idea if that could be the culprit?

**Comment by pfrazee** [comment]
Okay yep, mismatch between frontend and backend. Fixed!
