### ISSUE TITLE
Rewrite the Lexicon language

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#372]
We've encountered a number of challenges with Lexicon as it's currently designed which has led us to decide on an update.

- Code generated from Lexicons in stricter langs than Typescript (e.g. Go) struggle with the loose structuring of JSON-Schema
- Blobs require custom constraint definitions
- Query parameters require custom constraint definitions
- The "hash segment" of lexicon URIs currently use JSON-Pointers, which are brittle when used for definition-reuse due to their structural dependency. They're also verbose enough to discourage code reuse.

The rewrite will adhere closely to the current model, but it will move away from JSON-Schema so that we can more easily generate code and extend the language to match ATP's needs.

**Comment by dholms** [comment]
lol i guess we got this one done 😅 
https://github.com/bluesky-social/atproto/pull/658
