### ISSUE TITLE
Validate CIDs passed to PDS xrpc methods

### ISSUE THREAD

**Issue by devinivy** [bluesky-social/atproto#456]
There are a handful of `cid` parameters and inputs to the PDS xrpc methods.  We should consider validating these as CIDs, otherwise fail the request with a 400.  In some cases currently `CID.parse()` may be called on them, causing an error to be thrown that turns into a 500.

**Comment by dholms** [comment]
fixed w new cid format

https://github.com/bluesky-social/atproto/pull/658
