### ISSUE TITLE
Email confirmation during signup? Some questions

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#479]
Email confirmation is meant to solve two problems:

1. Give the PDS admin confidence the user owns the email
2. Ensure the user gave the correct email so that we can offer support (eg password reset)

It's unclear that proving ownership (1) is a priority since we don't make any trust decisions based on user email. Ensuring we can provide support (2) however is a priority.

Here are the options in from of us:

- A. Include a step during signup where a confirmation email is sent. Wait for the user to enter the code in the email (or click the link inside) before we allow signup to finish.
- B. Send a confirmation email with a code/link during signup but don't block signup for confirmation. Afterwards, ask the user to confirm. Give an option to fix their email.
- C. Send a confirmation email with **no** code during signup. Afterwards, ask the user if they received the email at the given address but don't bother with a confirmation code. Give an option to fix their email.

Given that proving ownership (1) is not a priority but providing support (2) is, I'm inclined to say options B or C are suitable, and that option C may be enough. All we're trying to do is help users avoid mistakes. It seems like that should be as low friction as possible.

Thoughts?

**Comment by devinivy** [comment]
Another reason I'd toss in there is to ensure emails aren't sent to non-existent addresses, which can affect email reputation.  Also would be nice to have some kind of paper trail for users getting signed-up without their permission.  So if we are requiring an email for signup already, I think we formally confirm the email address but allow the user to login and use the app without confirmation.  So that's a vote for B!

**Comment by arcalinea** [comment]
Right now, and up through the phase where we're pulling in people off the email list, we already know we have a valid email for them. So think this is eventually necessary once we move into open access phase, but we can table it for now. It adds extra friction to a signup process that is already made complicated by invite codes!

**Comment by dholms** [comment]
Worth pointing out that even though we know we have valid emails for them, there is no requirement that they signed up with the same email that the invite went out to

**Comment by Mike-E-angelo** [comment]
I am currently locked out of my account as the email that I thought I used is not working to get a code sent to me.  Is there somewhere that I can go to get this resolved?  Thank you for any assistance.

**Comment by bnewbold** [comment]
@Mike-E-angelo email <support@bsky.app>; it might take a while to get a response.
