### ISSUE TITLE
API for clearing out the user Avatar or Banner

### ISSUE THREAD

**Issue by arrygoo** [bluesky-social/atproto#508]
## Problem 
It seems like one can add an avatar or banner, but I can't find a way to delete them. Leaving avatar as undefined just ignores that field. 

## Solution
Add the ability to remove the user's avatar or banner

Please correct me if I'm wrong or if this capability already exists. :)

**Comment by devinivy** [comment]
I think you're right about that behavior 👍  We need a proper way to distinguish missing values from empty values in the `updateProfile` method.

Trying to think of the most natural way to fit this into xrpc— what if we turned `avatar` into a closed union that can accept something like `{ $type: 'app.bsky.system.empty' }`?

**Comment by pfrazee** [comment]
I think you want an open union (pretty rare you ever want a closed union, right?).

An "empty" object type makes sense though I wonder if we just need to add a null type to lexicon.

**Comment by pfrazee** [comment]
> My thought process was, these fields were already "closed" by virtue of not being a union, and we really just needed to add a way to mark them as empty

Hmm! I guess that's true, fair point.

> The boolean would probably get us by for now, but I'd totally support adding a null in there! Question, though— do refs in a union need to be objects so that they have a discriminator?

Oh right, we should get @whyrusleeping to weigh in on this. You may be right.

**Comment by dholms** [comment]
Hey @devinivy 
this is all wrapped up by https://github.com/bluesky-social/atproto/pull/554 right?

**Comment by devinivy** [comment]
Ah yeah, thanks for flagging that!
