### ISSUE TITLE
Add ways to show if someone is following the user

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#509]
Currently there's no efficient way to find out if a user follows you.

Here's what I'd suggest adding:

- Update `actor.getProfile`, `graph.getFollows`, and `graph.getFollowers` to include a boolean indicating if the actor follows you.
- Probably do the same with `actor.search` and `actor.getSuggestions`
- Not necessary but might be worth updating `graph.getFollows` to optionally take a target actor to quickly determine if someone follows a specific actor. Alternatively can add a separate method.

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/539
