### ISSUE TITLE
Add method to bulk-fetch profiles

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#513]
We've found a situation (custom, hardcoded suggested follow lists) where having a bulk fetch of profiles for a set of user IDs would be useful. We need to add an xrpc method to `app.bsky.actor` to provide this.

Options:

- A `getProfiles()` method which takes in a list of dids/handles and provides the same output as `getProfile()`
- Some other method name (`bulkFetch`?) which either gives less info than `getProfile()` to reduce the method cost, or takes a parameter specifying what info is needed.

Personally I'd prefer the `getProfiles()` approach if it performs well enough.

**Comment by devinivy** [comment]
Resolved by #532
