### ISSUE TITLE
Lexicon updates: new types, string formats

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#580]
- Add the following types to Lexicon
  - `bytes`
    - In CBOR, uses the binary tag
    - In JSON, looks like `{$type: 'bytes', value: string}` with value using a base64 encoding
  - `cid-internal-ref`
    - In CBOR, uses the link tag
    - In JSON, looks like `{$type: 'cid-internal-ref', value: string}` with value using a base64 encoding
- Remove the `datetime` type
- Add the `format` modifier to strings
  - This should apply additional validation to strings
- Add the following string formats:
  - `datetime`
  - `at-uri`
  - `did`
  - `cid`
- Update all lexicons as follows:
  - Change any `datetime` type to a `string` with the datetime format
  - Add formats to any strings that might benefit from them

**Comment by bnewbold** [comment]
In the example for `cid-internal-ref` for JSON, do you mean {$type: 'cid-internal-ref', value: string}`? If not, it seems like it would not safely round-trip without schema between CBOR and JSON.

**Comment by pfrazee** [comment]
Yes, apologies

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
