### ISSUE TITLE
Remove assertion and confirmation

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#586]
- Remove:
  - `app.bsky.graph.assertion`
  - `app.bsky.graph.confirmation`
  - `app.bsky.graph.assertMember`
  - `app.bsky.graph.assertCreator`

We think these are the right idea but they're not being used yet, so they can come back in the future

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
