### ISSUE TITLE
Add `app.bsky.richtext.facet`

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#587]
- Add `app.bsky.richtext.facet`
    - Has an `index` which is `#textSlice`
    - and `value` which is an open union of `#link` and `#mention`
    - `#link` has a `uri` field
    - `#mention` has a `did` field
- Update `app.bsky.feed.post`...
    - Mark `entities` as deprecated but leave it in
    - Add `facets` as an optional field
    - This will make migration smooth — we keep supporting `entities` but start writing and using `facets`
- Update notification indexing to read the `facets` field but keep around the old `entities` field with a plan to deprecate
- Reasoning
    - Entities was created before Lexicon was fleshed out and it needs to use specific types, especially because it has indexing implications
    - Different kinds of facets have different field needs
    - As we expand on content-types, we’ll need a more robust rich text system, which entities basically was
    - The term “entities” confused people

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
