### ISSUE TITLE
Modify string length calculations in validation

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#595]
- We use utf8 encoding for all strings
- We want to modify the validation logic as follows:
  - Count string lengths by grapheme clusters instead of utf16 codepoints (the current behavior)
    - See [https://stackoverflow.com/questions/54369513/how-to-count-the-correct-length-of-a-string-with-emojis-in-javascript](https://stackoverflow.com/questions/54369513/how-to-count-the-correct-length-of-a-string-with-emojis-in-javascript) for more info
  - We should also impose an additional constraint on byte length (utf8) of maxLength * 10 to avoid over-packing graphemes
- The grapheme-counting library should be included in the client-side API for convenience
- Reasoning:
    - We encode the cbor in utf8
    - Javascript is utf16 and that transposes well with utf8
    - Graphemes are what users perceive as characters or individual emojis, and string length limits are generally oriented towards UX

**Comment by bnewbold** [comment]
I am happy to help with testing this validator, and in particular having some test cases for cross-language testing (eg, ensuring consistent behavior in golang).

I specifically want to ensure that Bengali text will end up validated correctly.

**Comment by dholms** [comment]
I'd propose that we have two different constraints on string fields in lex:
- `maxLength`: max chars in utf8
- `maxGraphemes`: max chars counted by graphemes

Also, it looks like `Intl.Segmenter` has landed & works very well: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
