### ISSUE TITLE
Refactor RPC method names and various reused definitions

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#597]
We are doing a large refactor of the NSIDs, largely grouping them in namespaces which feel more intuitive and modifying methods to follow the multi-word verb convention. This issue also includes some changes covered by other issues as a reminder.

The changes:

Existing | New
-- | --
com.atproto.account.create | com.atproto.server.createAccount
com.atproto.account.createInviteCode | com.atproto.server.createInviteCode
com.atproto.account.delete | com.atproto.server.deleteAccount
com.atproto.account.get | com.atproto.server.getAccount
com.atproto.account.requestDelete | com.atproto.server.requestAccountDelete
com.atproto.account.requestPasswordReset | com.atproto.server.requestPasswordReset
com.atproto.account.resetPassword | com.atproto.server.resetPassword
com.atproto.admin.blob | com.atproto.admin.defs
com.atproto.admin.moderationAction | com.atproto.admin.defs
com.atproto.admin.moderationReport | com.atproto.admin.defs
com.atproto.admin.record | com.atproto.admin.defs
com.atproto.admin.repo | com.atproto.admin.defs
com.atproto.blob.upload | com.atproto.repo.uploadBlob
com.atproto.handle.resolve | com.atproto.identity.resolveHandle
com.atproto.handle.update | com.atproto.identity.updateHandle
com.atproto.repo.batchWrite | com.atproto.repo.applyWrites
com.atproto.repo.describe | com.atproto.repo.describeRepo
com.atproto.repo.recordRef | DELETE (admin should use strongRef)
com.atproto.repo.repoRef | com.atproto.admin.defs
com.atproto.report.create | com.atproto.moderation.createReport
com.atproto.report.reasonType | com.atproto.moderation.defs
com.atproto.report.subject | com.atproto.moderation.defs
com.atproto.server.getAccountsConfig | com.atproto.server.describeServer
com.atproto.session.create | com.atproto.server.createSession
com.atproto.session.delete | com.atproto.server.deleteSession
com.atproto.session.get | com.atproto.server.getSession
com.atproto.session.refresh | com.atproto.server.refreshSession
com.atproto.sync.subscribeAllRepos | com.atproto.sync.subscribeRepos
app.bsky.actor.ref | 1. Move the view-defs into app.bsky.actor.defs; 2. Remove the “main” and use “did” in follows, assertions, and confirmations |
| app.bsky.actor.search | app.bsky.search.searchActor |
| app.bsky.actor.searchTypeahead | app.bsky.search.searchActorTypeahead |
| app.bsky.actor.updateProfile | DELETE |
| app.bsky.feed.feedViewPost | app.bsky.feed.defs |
| app.bsky.feed.getVotes | app.bsky.feed.getLikes |
| app.bsky.feed.setVote | DELETE |
| app.bsky.feed.vote | app.bsky.feed.like |
| app.bsky.graph.assertCreator | DELETE |
| app.bsky.graph.assertMember | DELETE |
| app.bsky.graph.assertion | DELETE |
| app.bsky.graph.confirmation | DELETE |
| app.bsky.graph.follow | Keep name; change declRef to a did string |
| app.bsky.graph.mute | app.bsky.graph.muteActor |
| app.bsky.graph.unmute | app.bsky.graph.unmuteActor |
| app.bsky.notification.getCount | app.bsky.notification.getUnreadCount |
| app.bsky.notification.list | app.bsky.notification.listNotifications |
| app.bsky.system.actorUser | DELETE |
| app.bsky.system.declRef | DELETE |
| app.bsky.system.declaration | DELETE |

This will result in the following final NSID listing:

```
com.atproto.admin.defs
com.atproto.admin.getModerationAction
com.atproto.admin.getModerationActions
com.atproto.admin.getModerationReport
com.atproto.admin.getModerationReports
com.atproto.admin.getRecord
com.atproto.admin.getRepo
com.atproto.admin.resolveModerationReports
com.atproto.admin.reverseModerationAction
com.atproto.admin.searchRepos
com.atproto.admin.takeModerationAction

com.atproto.identity.resolveHandle
com.atproto.identity.updateHandle

com.atproto.moderation.createReport
com.atproto.moderation.defs

com.atproto.repo.applyWrites
com.atproto.repo.createRecord
com.atproto.repo.describeRepo
com.atproto.repo.deleteRecord
com.atproto.repo.getRecord
com.atproto.repo.listRecords
com.atproto.repo.putRecord
com.atproto.repo.strongRef
com.atproto.repo.uploadBlob

com.atproto.server.createAccount
com.atproto.server.createInviteCode
com.atproto.server.createSession
com.atproto.server.deleteAccount
com.atproto.server.deleteSession
com.atproto.server.describeServer
com.atproto.server.getAccount
com.atproto.server.getSession
com.atproto.server.refreshSession
com.atproto.server.requestAccountDelete
com.atproto.server.requestPasswordReset
com.atproto.server.resetPassword

com.atproto.sync.getCheckout
com.atproto.sync.getCommitPath
com.atproto.sync.getHead
com.atproto.sync.getRecord
com.atproto.sync.getRepo
com.atproto.sync.subscribeRepos

app.bsky.actor.defs
app.bsky.actor.getProfile
app.bsky.actor.getProfiles
app.bsky.actor.getSuggestions
app.bsky.actor.profile

app.bsky.embed.external
app.bsky.embed.images

app.bsky.feed.defs
app.bsky.feed.getAuthorFeed
app.bsky.feed.getLikes
app.bsky.feed.getPostThread
app.bsky.feed.getRepostedBy
app.bsky.feed.getTimeline
app.bsky.feed.like
app.bsky.feed.post
app.bsky.feed.repost

app.bsky.graph.follow
app.bsky.graph.getFollowers
app.bsky.graph.getFollows
app.bsky.graph.getMutes
app.bsky.graph.muteActor
app.bsky.graph.unmuteActor

app.bsky.notification.getUnreadCount
app.bsky.notification.listNotifications
app.bsky.notification.updateSeen

app.bsky.richtext.facet

app.bsky.search.searchActor
app.bsky.search.searchActorTypeahead
```

**Comment by myConsciousness** [comment]
Oops, I just found a document about versioning :)

- https://atproto.com/guides/lexicon#versioning

**Comment by pfrazee** [comment]
Yeah this is part of a one-time breaking refactor which will not be possible after the protocol hits v1. The only reason we can do this now is because we're in beta.

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
