### ISSUE TITLE
Duplicate notifications are generated for posts that are both replies and mentions

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#612]
I noticed duplicate notifications:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1270099/222281585-bfa8f00e-5ee1-40fc-9b73-e1af1851129e.png">

Turns out it's because they mentioned me _and_ replied. I can dedup this in the client if it's terribly difficult to solve in the server, though that will cause the notification count to be slightly inflated.

**Comment by pfrazee** [comment]
Related: https://github.com/bluesky-social/social-app/issues/240

**Comment by dholms** [comment]
What would be the preferred "reason" here?

**Comment by pfrazee** [comment]
Probably reply
