### ISSUE TITLE
A few changes to the record embeds

### ISSUE THREAD

**Issue by pfrazee** [bluesky-social/atproto#619]
Hey @devinivy now that I'm finally futzing with the record embeds, I'm hitting a couple things I could use changes on. We could group this into the lexicon refactor.

- We need the `indexedAt` field somewhere in there I think. Right now we're using `createdAt` which can be effed with.
- I was wrong. We do need the presented form to have the presented embeds of the embedded record. Specifically for images. My bad.
- Right now the presented form ends up with `record.record`. Not a huge deal but if inspiration hits, it'd be great to have another name for the outer bit.

**Comment by pfrazee** [comment]
We also need to check on:

- Notifications created for quote posts
- Quote post count metrics

**Comment by dholms** [comment]
fixed https://github.com/bluesky-social/atproto/pull/658
