### ISSUE TITLE
`app.bsky.actor.getProfiles` reads only the first `actors`?

### ISSUE THREAD

**Issue by myConsciousness** [bluesky-social/atproto#640]
Hi amazing developers,

I'm trying to call `app.bsky.actor.getProfiles` to get profile information for multiple users. However, when I called this endpoint, it seemed to only read the user ID set in the leading `actors`.

For example, I called the endpoint as follows:

- GET https://bsky.social/xrpc/app.bsky.actor.getProfiles?actors=shinyakato.dev&actors=mayako.bsky.social

But, the only ones returned are those of the user set to the earliest `actors` as shown below.

```json
{
  "profiles": [
    {
      "did": "did:plc:iijrtk7ocored6zuziwmqq3c",
      "handle": "shinyakato.dev",
      "displayName": "Shinya Kato",
      "description": "Dart/Flutter enthusiast. The author of many Dart/Flutter packages such as twitter_api_v2, twitter_oauth2_pkce, mastodon_api and etc.\n\nYou can find me on GitHub:\nhttps://github.com/myConsciousness",
      "avatar": "https://cdn.bsky.social/imgproxy/JF97YphLyIEWfq4KJNO_ZCYm9v_zNcRj7sSB8UZrRBw/rs:fill:1000:1000:1:0/plain/bafkreidqn4z6ocv5snxuqguarboozqdusam2tehccnu23yab7g2sgv64dq@jpeg",
      "banner": "https://cdn.bsky.social/imgproxy/0ijMnNxGs3aYg9Xsb5YkfehBkZo2WRJReLgMtljXPM0/rs:fill:3000:1000:1:0/plain/bafkreiaz67sqpaacxjtbj7texvnz5tlnfpthman4kvciymxg2jc2vayd4m@jpeg",
      "followsCount": 175,
      "followersCount": 102,
      "postsCount": 73,
      "declaration": {
        "cid": "bafyreid27zk7lbis4zw5fz4podbvbs4fc5ivwji3dmrwa6zggnj4bnd57u"
      },
      "viewer": { "muted": false },
      "myState": { "muted": false },
      "creator": "did:plc:iijrtk7ocored6zuziwmqq3c",
      "indexedAt": "2023-03-07T03:00:49.705Z"
    }
  ]
}
```

I also tried the possibility of the `actors` parameter being comma or space delimited, but these approaches did not return anything. Is there a problem with the structure of the request array?

Thank you.

**Comment by devinivy** [comment]
The way you wrote it in your example is correct:
```
/xrpc/app.bsky.actor.getProfiles?actors=some.handle.dev&actors=some.other.handle.dev
```

If there's not a match on a given handle then it is omitted from the result set.  Is it possible one of the handles you included in the `actors` parameter is no longer being used?  That would be consistent with the intended behavior.

Another thought— a way you can test your hypothesis is by trying each `actors` individually and checking whether each one of them gets a result when its provided on its own.

**Comment by myConsciousness** [comment]
Hi @devinivy ,

I just tried and was able to get multiple Actors. I guess the target user changed a handle to custom domain. 

It works perfectly, thanks anyway!
