### ISSUE TITLE
Mismatched description for app.bsky.actor.updateProfile lexicon reference

### ISSUE THREAD

**Issue by Amazingca** [bluesky-social/atproto#644]
https://github.com/bluesky-social/atproto/blob/7cc48089073aa71e139fa441c53f6141fba69936/lexicons/app/bsky/actor/updateProfile.json#L7

It seems that this is the description used for `app.bsky.notification.updateSeen`:

https://github.com/bluesky-social/atproto/blob/7cc48089073aa71e139fa441c53f6141fba69936/lexicons/app/bsky/notification/updateSeen.json#L7

**Comment by dholms** [comment]
got it into the lex refactor feature branch here: https://github.com/bluesky-social/atproto/pull/658
