### ISSUE TITLE
Can't the `createdAt` in `com.atproto.repo.createRecord` be optional?

### ISSUE THREAD

**Issue by myConsciousness** [bluesky-social/atproto#650]
Hi,

I'm trying out an implementation that uses `com.atproto.repo.createRecord` to post to Bluesky, why is `createdAt` required? If this parameter is not specified, we can expect it to be specified in the current time (UTC time), which can be handled by the server receiving this request, can't it?

Sorry for the Dart code, but I have implemented the following. 

```dart
  Future<ATProtoResponse<Record>> createPost({
    required String text,
    DateTime? createdAt,
  }) async =>
      await atproto.repositories.createRecord(
        collection: 'app.bsky.feed.post',
        record: {
          'text': text,

          // ↓ Can't handle this on the server?
          'createdAt': (createdAt ?? DateTime.now()).toUtc().toIso8601String(), 
        },
      );
```

As per the comment in the code above, can we make `createdAt` optional, and if not specified, can the server treat it as the current time (UTC time)?

**Comment by pfrazee** [comment]
Another way to put this -- not every record has a `createdAt`, so the PDS would have to read the schemas of the posts to do this, and the goal right now is for servers not to do that. We're cheating in a few places but the goal is to remove those cheats in the long run.

**Comment by dholms** [comment]
Closing for now, but feel free to keep chatting if you like
