### ISSUE TITLE
com.atproto.repo.createRecord failed after updating Repo v2

### ISSUE THREAD

**Issue by KingYoSun** [bluesky-social/atproto#656]
Hi, I'm 3rd party PDS server administrator(https://boobee.blue).
My server [repo](https://github.com/KingYoSun/atproto) merged commit 9baf9b2 (Repo v2) and it got the following error in `com.atproto.repo.createRecord`.

<details>
<summary>error log</summary>
<pre>
<code>
{
    "level": 50,
    "time": 1678728514790,
    "pid": 7,
    "hostname": "boobee.blue",
    "name": "xrpc-server",
    "err": {
        "type": "UnexpectedObjectError",
        "message": "unexpected object at bafyreid7jy4nhzvddegbgof2ulxls7ovdbx4z3s72wrqu36bamol6zlkyu, expected: commit",
        "stack": "Error: unexpected object at bafyreid7jy4nhzvddegbgof2ulxls7ovdbx4z3s72wrqu36bamol6zlkyu, expected: commit\n    at parseObj (/app/packages/repo/src/parse.ts:28:11)\n    at SqlRepoStorage.attemptRead (/app/packages/repo/src/storage/readable-blockstore.ts:18:18)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at SqlRepoStorage.readObjAndBytes (/app/packages/repo/src/storage/readable-blockstore.ts:25:18)\n    at SqlRepoStorage.readObj (/app/packages/repo/src/storage/readable-blockstore.ts:33:17)\n    at Function.load (/app/packages/repo/src/repo.ts:106:20)\n    at RepoService.formatCommit (/app/packages/pds/src/services/repo/index.ts:90:18)\n    at RepoService.processWrites (/app/packages/pds/src/services/repo/index.ts:67:24)\n    at RepoService.processCreatesAndDeletes (/app/packages/pds/src/services/repo/index.ts:54:5)\n    at <anonymous> (/app/packages/pds/src/api/com/atproto/repo.ts:201:9)",
        "cid": {
            "code": 113,
            "version": 1,
            "hash": {
                (omitted)
            }
        },
        "def": {
            "name": "commit",
            "schema": {
                "_def": {
                    "unknownKeys": "strip",
                    "catchall": {
                        "_def": {
                            "typeName": "ZodNever"
                        }
                    },
                    "typeName": "ZodObject"
                },
                "_cached": {
                    "shape": {
                        "did": {
                            "_def": {
                                "checks": [],
                                "typeName": "ZodString"
                            }
                        },
                        "version": {
                            "_def": {
                                "checks": [],
                                "typeName": "ZodNumber"
                            }
                        },
                        "prev": {
                            "_def": {
                                "innerType": {
                                    "_def": {
                                        "schema": {
                                            "_def": {
                                                "schema": {
                                                    "_def": {
                                                        "typeName": "ZodAny"
                                                    },
                                                    "_any": true
                                                },
                                                "typeName": "ZodEffects",
                                                "effect": {
                                                    "type": "refinement"
                                                }
                                            }
                                        },
                                        "typeName": "ZodEffects",
                                        "effect": {
                                            "type": "transform"
                                        }
                                    }
                                },
                                "typeName": "ZodNullable"
                            }
                        },
                        "data": {
                            "_def": {
                                "schema": {
                                    "_def": {
                                        "schema": {
                                            "_def": {
                                                "typeName": "ZodAny"
                                            },
                                            "_any": true
                                        },
                                        "typeName": "ZodEffects",
                                        "effect": {
                                            "type": "refinement"
                                        }
                                    }
                                },
                                "typeName": "ZodEffects",
                                "effect": {
                                    "type": "transform"
                                }
                            }
                        },
                        "sig": {
                            "_def": {
                                "schema": {
                                    "_def": {
                                        "typeName": "ZodAny"
                                    },
                                    "_any": true
                                },
                                "typeName": "ZodEffects",
                                "effect": {
                                    "type": "refinement"
                                }
                            }
                        }
                    },
                    "keys": [
                        "did",
                        "version",
                        "prev",
                        "data",
                        "sig"
                    ]
                }
            }
        }
    },
    "msg": "unhandled exception in xrpc method com.atproto.repo.createRecord"
}
</pre>
</code>
</details>
When I revert to 937ab98(migrations is only remain), the error stopped.

[Question] Do I need to do anything special to update to Repo v2?

**Comment by dholms** [comment]
We were not expecting anyone to be running a PDS at the moment & introduced breaking changes. This involved a data migration on our side, but we did not merge that migration to main.

We're approaching stability of the protocol & won't be doing such changes anymore.

If you want to bring your current data up to date, probably the best way is to run the `repo-v2.ts` migration on this branch: https://github.com/bluesky-social/atproto/pull/643

**Comment by dholms** [comment]
Yup yup 👍 

Let me know how it goes for you. You might even be able to just run that `testRun` function with `ts-node` (switching out your db creds & server key) to perform the migration 👍

**Comment by KingYoSun** [comment]
Migration was completed successfully. Thanks!!!
After reading #643, I ran the entire #643 instead of testRun because I also needed to migrate plcKey.

**Comment by dholms** [comment]
nice glad you got it going!
