### ISSUE TITLE
TypeError: undefined is not a function when calling API in React Native app

### ISSUE THREAD

**Issue by richstokes** [bluesky-social/atproto#667]
Hi there!

I spent a couple of evenings trying to get this work. Basically trying to create a simple React Native client (using expo). 

I have a basic login screen that does this:
```
import { AtpAgent } from "@atproto/api";

export function attemptLogin(
    service,
    identifier,
    password
) {
    console.log("Logging in to", service, "as", identifier);
    const agent = new AtpAgent({ service: service });

    agent.login({ identifier: identifier, password: password }).then(
        ({ success, data }) => {
            if (!success) {
                console.error("Login failed");
                return;
            }
        },
        (reason) => {
            console.error("Login failure", reason);
        }
    );
}
```

Which results in `TypeError: undefined is not a function`. I've tried various incantations of invoking the function, but I always get this error.

At this point I am wondering if there's some compatability issue with expo. 

I'm using `"@atproto/api": "^0.1.3"`

**Comment by dholms** [comment]
It should work fine with expo, our application uses Expo. But maybe @pfrazee knows some special magic that has to be done?

So it's considering `agent.login` to be undefined? can you log what `agent` looks like?

using typescript may help as well

**Comment by richstokes** [comment]
Good idea, logging agent I get this which seems incomplete:

```
agent: {"_baseClient": {"xrpc": {"fetch": [Function bound _fetch], "lex": [Lexicons]}}, "_persistSession": undefined, "api": {"_baseClient": {"xrpc": [Client]}, "app": {"_service": [Circular], "bsky": [_BskyNS]}, "com": {"_service": [Circular], "atproto": [_AtprotoNS]}, "xrpc": {"baseClient": [Client], "headers": [Object], "uri": [URL]}}, "service": "http://localhost:2583/"}
```

**Comment by dholms** [comment]
That's really strange 🤔 

My best guess is that it seems like an outdated package. Doublecheck your lock file to ensure that `@atproto/api@0.1.3` is installed?

**Comment by richstokes** [comment]
Lockfile is all good, tried wiping node_modules, clearing expo cache, etc and reinstalling everything, no dice 🤔

**Comment by richstokes** [comment]
Interesting, if we log `agent.login` it confirms that it is, in fact, a function. So really not sure what's going wrong here 😿 

```
const agent = new AtpAgent({ service: service });
console.log("agent.login", agent.login);
```
```
 LOG  agent.login [Function login]
 ERROR  Login failure [TypeError: undefined is not a function]
```


Do we need to do anything special with tsconfig, babel config or similar? I'm not clear on how React Native knows how to load TS libraries and wondering if that might have something to do with it.

I tried on a totally fresh expo TS app and got the same behavior btw.

**Comment by dholms** [comment]
really strange 🤔 

it wouldn't be `.then` that it's calling not a function would it?

maybe try with async/await?

tough to tell when we don't know what's undefined 😅 

do other methods on agent work? maybe try some other methods like createAccount?

**Comment by richstokes** [comment]
Tried it with async/await, same behavior 

Just tried `createAccount` - exact same problem 🤔

**Comment by pfrazee** [comment]
Not sure if this will solve it, but one thing RN requires is a custom fetch function. Here's mine:

```typescript
import AtpAgent from '@atproto/api'
import RNFS from 'react-native-fs'

const GET_TIMEOUT = 15e3 // 15s
const POST_TIMEOUT = 60e3 // 60s

export function doPolyfill() {
  AtpAgent.configure({fetch: fetchHandler})
}

interface FetchHandlerResponse {
  status: number
  headers: Record<string, string>
  body: ArrayBuffer | undefined
}

async function fetchHandler(
  reqUri: string,
  reqMethod: string,
  reqHeaders: Record<string, string>,
  reqBody: any,
): Promise<FetchHandlerResponse> {
  const reqMimeType = reqHeaders['Content-Type'] || reqHeaders['content-type']
  if (reqMimeType && reqMimeType.startsWith('application/json')) {
    reqBody = JSON.stringify(reqBody)
  } else if (
    typeof reqBody === 'string' &&
    (reqBody.startsWith('/') || reqBody.startsWith('file:'))
  ) {
    if (reqBody.endsWith('.jpeg') || reqBody.endsWith('.jpg')) {
      // HACK
      // React native has a bug that inflates the size of jpegs on upload
      // we get around that by renaming the file ext to .bin
      // see https://github.com/facebook/react-native/issues/27099
      // -prf
      const newPath = reqBody.replace(/\.jpe?g$/, '.bin')
      await RNFS.moveFile(reqBody, newPath)
      reqBody = newPath
    }
    // NOTE
    // React native treats bodies with {uri: string} as file uploads to pull from cache
    // -prf
    reqBody = {uri: reqBody}
  }

  const controller = new AbortController()
  const to = setTimeout(
    () => controller.abort(),
    reqMethod === 'post' ? POST_TIMEOUT : GET_TIMEOUT,
  )

  const res = await fetch(reqUri, {
    method: reqMethod,
    headers: reqHeaders,
    body: reqBody,
    signal: controller.signal,
  })

  const resStatus = res.status
  const resHeaders: Record<string, string> = {}
  res.headers.forEach((value: string, key: string) => {
    resHeaders[key] = value
  })
  const resMimeType = resHeaders['Content-Type'] || resHeaders['content-type']
  let resBody
  if (resMimeType) {
    if (resMimeType.startsWith('application/json')) {
      resBody = await res.json()
    } else if (resMimeType.startsWith('text/')) {
      resBody = await res.text()
    } else {
      throw new Error('TODO: non-textual response body')
    }
  }

  clearTimeout(to)

  return {
    status: resStatus,
    headers: resHeaders,
    body: resBody,
  }
}
```

**Comment by richstokes** [comment]
Thanks - I'm sure that's part of it, but I can't figure out how to tie it all together.

Full disclosure, this is my first attempt learning RN 😹  - maybe not the easiest thing to start off with. But I'm normally pretty good at following instructions/figuring stuff out. This all seems really confusing/somewhat contrived. Not sure how much of that is just how RN be. 

Is it fair to say this is a downside of not using a "regular"/HTTP API? I'm used to just being able post json requests and parse the response. 🤔

**Comment by pfrazee** [comment]
Well it actually is just a regular http api. The agent is just a wrapper library, but it’s all just GETs and POSTs over httpOn Mar 17, 2023, at 6:06 PM, Rich Stokes ***@***.***> wrote:﻿
Thanks - I'm sure that's part of it, but I can't figure out how to tie it all together.
Full disclosure, this is my first attempt learning RN 😹  - maybe not the easiest thing to start off with. But I'm normally pretty good at following instructions/figuring stuff out. This all seems really confusing/somewhat contrived. Not sure how much of that is just how RN be.
Is it fair to say this is a downside of not using a "regular"/HTTP API? I'm used to just being able post json requests and parse the response. 🤔

**Comment by dholms** [comment]
yeah if you like you can just hit the api with whatever agent you like:
`axios.post('https://bsky.social/xrpc/com.atproto.server.createSession', { identifier, password])`

**Comment by richstokes** [comment]
Oh yeah. Posting HTTP directly is way easier. Maybe I misunderstood the purpose of this API, but should it not be trying to abstract away complexity and make things easier to work with?

That said, I appreciate it's all early days :-) 🍻

**Comment by dholms** [comment]
It gives you a typesafe extensible & generable api package for any service that implements lexicon schemas. Running in node is super simple as a result. Handles encodings, parsing, schema validation, error management, etc.

The complexity is with RN being a bit screwy around `fetch` & requiring a custom function

**Comment by dholms** [comment]
Gonna close for now. But feel free to keep chatting if anything comes up!
