### ISSUE TITLE
ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by richstokes** [bluesky-social/atproto#743]
Using React Native via expo, with the just-released (0.2.0) API, and following the [rn doc](https://github.com/bluesky-social/atproto/blob/main/packages/api/docs/rn-fetch-handler.ts) I get this error:

```
ReferenceError: Property 'TextEncoder' doesn't exist, js engine: hermes
```

I tried [this workaround](https://github.com/facebook/hermes/issues/948#issuecomment-1484240071), but that doesn't seem to work either. I'm not sure where `TextEncoder` is supposed to come from. Here's my entire component. Am I doing something obviously wrong here?

```
import { BskyAgent, stringifyLex, jsonToLex } from '@atproto/api'
import RNFS from 'react-native-fs'

const GET_TIMEOUT = 15e3 // 15s
const POST_TIMEOUT = 60e3 // 60s

export function doPolyfill() {
  console.log("doPolyfill called")
  BskyAgent.configure({ fetch: fetchHandler })
}

interface FetchHandlerResponse {
  status: number
  headers: Record<string, string>
  body: ArrayBuffer | undefined
}

async function fetchHandler(
  reqUri: string,
  reqMethod: string,
  reqHeaders: Record<string, string>,
  reqBody: any,
): Promise<FetchHandlerResponse> {
  console.log("fetchHandler called")
  const reqMimeType = reqHeaders['Content-Type'] || reqHeaders['content-type']
  if (reqMimeType && reqMimeType.startsWith('application/json')) {
    reqBody = stringifyLex(reqBody)
  } else if (
    typeof reqBody === 'string' &&
    (reqBody.startsWith('/') || reqBody.startsWith('file:'))
  ) {
    if (reqBody.endsWith('.jpeg') || reqBody.endsWith('.jpg')) {
      // HACK
      // React native has a bug that inflates the size of jpegs on upload
      // we get around that by renaming the file ext to .bin
      // see https://github.com/facebook/react-native/issues/27099
      // -prf
      const newPath = reqBody.replace(/\.jpe?g$/, '.bin')
      await RNFS.moveFile(reqBody, newPath)
      reqBody = newPath
    }
    // NOTE
    // React native treats bodies with {uri: string} as file uploads to pull from cache
    // -prf
    reqBody = { uri: reqBody }
  }

  const controller = new AbortController()
  const to = setTimeout(
    () => controller.abort(),
    reqMethod === 'post' ? POST_TIMEOUT : GET_TIMEOUT,
  )

  const res = await fetch(reqUri, {
    method: reqMethod,
    headers: reqHeaders,
    body: reqBody,
    signal: controller.signal,
  })

  const resStatus = res.status
  const resHeaders: Record<string, string> = {}
  res.headers.forEach((value: string, key: string) => {
    resHeaders[key] = value
  })
  const resMimeType = resHeaders['Content-Type'] || resHeaders['content-type']
  let resBody
  if (resMimeType) {
    if (resMimeType.startsWith('application/json')) {
      resBody = jsonToLex(await res.json())
    } else if (resMimeType.startsWith('text/')) {
      resBody = await res.text()
    } else {
      throw new Error('TODO: non-textual response body')
    }
  }

  clearTimeout(to)

  return {
    status: resStatus,
    headers: resHeaders,
    body: resBody,
  }
}

async function bskyLogin(handle, pw) {
  doPolyfill();
  const agent = new BskyAgent({ service: 'https://bsky.social' })
  console.log('agent: ', agent)
  console.log('bskyLogin called for handle: ' + handle, 'pw: ' + pw)
  try {
    const session = await agent.login({ identifier: handle, password: pw })
    console.log('session: ', session)
  } catch (error) {
    console.log('bskyLogin error: ', error);
  }
  return session
}


export default bskyLogin;
```
&nbsp;

If I set `const { TextEncoder, TextDecoder } = require('text-encoding');` at the top, AND set `"jsEngine": "jsc",` in my `app.json`, the error changes to:

` LOG  bskyLogin error:  [TypeError: this._url.endsWith is not a function. (In 'this._url.endsWith('/')', 'this._url.endsWith' is undefined)]` -- I'm not sure if thats progress or not!

**Comment by pfrazee** [comment]
Looks like react native? Here is my current polyfill file:

```typescript
import 'fast-text-encoding'
import Graphemer from 'graphemer'
export {}

/**
https://github.com/MaxArt2501/base64-js
The MIT License (MIT)
Copyright (c) 2014 MaxArt2501
 */

const b64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
// Regular expression to check formal correctness of base64 encoded strings
const b64re =
  /^(?:[A-Za-z\d+\/]{4})*?(?:[A-Za-z\d+\/]{2}(?:==)?|[A-Za-z\d+\/]{3}=?)?$/

globalThis.atob = (str: string): string => {
  // atob can work with strings with whitespaces, even inside the encoded part,
  // but only \t, \n, \f, \r and ' ', which can be stripped.
  str = String(str).replace(/[\t\n\f\r ]+/g, '')
  if (!b64re.test(str)) {
    throw new TypeError(
      "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.",
    )
  }

  // Adding the padding if missing, for semplicity
  str += '=='.slice(2 - (str.length & 3))
  var bitmap,
    result = '',
    r1,
    r2,
    i = 0
  for (; i < str.length; ) {
    bitmap =
      (b64.indexOf(str.charAt(i++)) << 18) |
      (b64.indexOf(str.charAt(i++)) << 12) |
      ((r1 = b64.indexOf(str.charAt(i++))) << 6) |
      (r2 = b64.indexOf(str.charAt(i++)))

    result +=
      r1 === 64
        ? String.fromCharCode((bitmap >> 16) & 255)
        : r2 === 64
        ? String.fromCharCode((bitmap >> 16) & 255, (bitmap >> 8) & 255)
        : String.fromCharCode(
            (bitmap >> 16) & 255,
            (bitmap >> 8) & 255,
            bitmap & 255,
          )
  }
  return result
}

const splitter = new Graphemer()
globalThis.Intl = globalThis.Intl || {}

// @ts-ignore we're polyfilling -prf
globalThis.Intl.Segmenter =
  // @ts-ignore we're polyfilling -prf
  globalThis.Intl.Segmenter ||
  class Segmenter {
    constructor() {}
    // NOTE
    // this is not a precisely correct polyfill but it's sufficient for our needs
    // -prf
    segment = splitter.iterateGraphemes
  }
```

Relevant packages are `fast-text-encoding@1.0.6` and `graphemer@1.4.0`.

**Comment by richstokes** [comment]
Yep, RN -- do you put that inside the doPollyfill function?

**Comment by pfrazee** [comment]
Oh nope— I put this at the start of the bundle before anything else gets imported On Mar 31, 2023, at 7:44 PM, Rich Stokes ***@***.***> wrote:﻿
Yep, RN -- do you put that inside the doPollyfill function?

**Comment by richstokes** [comment]
Hmm. No dice. If you get a chance I'd be really interested to know if creating a blank RN app in expo and trying to call the API per the docs works for you. Feels like something fundamental is missing from the instructions 🤔

**Comment by pfrazee** [comment]
Sure thing, I'll see if we can't get that done soon

**Comment by richstokes** [comment]
Also noticed the [doc here](https://github.com/bluesky-social/atproto/tree/main/packages/api)

says to

`import {AtpAgentFetchHeaders, AtpAgentFetchHandlerResponse} from '@atproto/api'` when using a custom fetch implementation, however AtpAgentFetchHeaders' apparently doesn't exist 🤔 not sure if thats needed or not

**Comment by pfrazee** [comment]
I created an example repo for you: https://github.com/pfrazee/example-atproto-rn-app

Turns out I also needed to add a better `URL` polyfill. I'm unsure why I haven't needed that in our social app, but it's in the example above. I'll check into that doc -- probably out of date.

**Comment by richstokes** [comment]
It works! Thank you so much, that really helped!

**Comment by pfrazee** [comment]
You bet!

**Comment by SoliMouse** [comment]
I had the same issue and was able to resolve by putting this line at the top of the App.js

`import "text-encoding-polyfill";`

Full File:

`import "text-encoding-polyfill";
import "react-native-gesture-handler";
import React from "react";
import { HStack, NativeBaseProvider, VStack, extendTheme } from "native-base";
import { QueryClient, QueryClientProvider } from "react-query";
// interal
import { Navigation } from "./src/navigation/navigation";
import { AuthContextProvider } from "./src/services/auth.context";

const queryClient = new QueryClient();
const theme = extendTheme({
  useSystemColorMode: true,
  initialColorMode: "light",
  colors: {
    primary: {
      50: "#cce4ff",
      100: "#99c9ff",
      200: "#66adff",
      300: "#3392ff",
      400: "#1b7aff",
      500: "#0560ff",
      600: "#044ecd",
      700: "#033b9a",
      800: "#022867",
      900: "#011534",
    },
  },
});

export default function App() {
  return (
    <NativeBaseProvider theme={theme}>
      <AuthContextProvider>
        <QueryClientProvider client={queryClient}>
          <HStack flex={1} justifyContent={"center"}>
            <VStack flex={1} maxWidth={768}>
              <Navigation />
            </VStack>
          </HStack>
        </QueryClientProvider>
      </AuthContextProvider>
    </NativeBaseProvider>
  );
}
`
