### ISSUE TITLE
Users can invite infinity in bsky.social

### ISSUE THREAD

**Issue by KingYoSun** [bluesky-social/atproto#766]
Every user can invite infinity in bsky.social.
User consume invite code, then the code is replenished to 5 immediately.
Probably because there is no logic in the `couldCreate` calculation in `packages/pds/src/api/com/atproto/server/getAccountInviteCodes.ts` to subtract the number of codes already created.
Currently, it is simply `Math.floor( accountLifespan / ctx.cfg.userInviteInterval )`.

**Comment by pfrazee** [comment]
Nice catch, yeah that was it. We fixed in https://github.com/bluesky-social/atproto/pull/767

Going to optimistically close this

**Comment by JonazBR** [comment]
i need invite code

**Comment by hossamkarimo** [comment]
I need invite code please

**Comment by rodrigoromo28** [comment]
hi, any one has an invite code left?

**Comment by toneji** [comment]
Pleasw send me invite code.
Thank you.

**Comment by selinrv** [comment]
Can someone send me an invite, pls?

**Comment by hossamkarimo** [comment]
Can i find any way to get the invite code
