### ISSUE TITLE
Cannot find ghcr.io repository

### ISSUE THREAD

**Issue by inductor** [bluesky-social/atproto#786]
In CIs that ran in https://github.com/bluesky-social/atproto/actions/workflows/build-and-push-pds-ghcr.yaml tells you that the container images are supposed to be in `ghcr.io/bluesky-social/atproto`, but I don't see any images in https://github.com/orgs/bluesky-social/packages.

**Comment by inductor** [comment]
@dholms @Jacob2161 Looks like you guys created the GHA workflow, is it possible for you to check if this package is private? :)

**Comment by dholms** [comment]
Sorry thought we had made it public. Just fixed 👌 

https://github.com/orgs/bluesky-social/packages
