### ISSUE TITLE
[Question] What mean of serverDid?

### ISSUE THREAD

**Issue by KingYoSun** [bluesky-social/atproto#813]
The serverDid is required to build the PDS, but it is only set in config of the atproto implementation and is not specifically used.

I am running a 3rd party PDS (boobee.blue) and I have not utilized serverDid in my PDS specifically because I created the DID directly in plc.directory.
So, this DID is not resolving: https://boobee.blue/xrpc/com.atproto.sync.getRepo?did=did:plc:bsylrfe45wyydwk5gnqo7mrhg32symsk2bgtzunbdgfmg4pxatia

Why serverDid is necessary?

**Comment by dholms** [comment]
You're correct that we don't use it yet. 

But we're planning on services in the network each having a DID. It helps with addressing & authorization.

You can set it to a temporary value, for instance `did:example:temporary` until the value starts to be used

**Comment by KingYoSun** [comment]
Thanks for answer question! I understand the circumstances.
