### ISSUE TITLE
`xrpc/com.atproto.repo.createRecord?collection=app.bsky.feed.post` does not strip extraneous object keys

### ISSUE THREAD

**Issue by jesopo** [bluesky-social/atproto#832]
```
$ curl -s "https://bsky.social/xrpc/com.atproto.repo.getRecord?repo=jesopo-test.bsky.social&collection=app.bsky.feed.post&rkey=3jtlrb3nfu226" | jq
{
  "uri": "at://did:plc:sdeyff35uikqhp7tiu7p4dbd/app.bsky.feed.post/3jtlrb3nfu226",
  "cid": "bafyreidvuc6sx5f5ntboglzhgmkexk3kcentsyfnlmrtml2fqbwhjnu7cm",
  "value": {
    "asd": "what happens to arbitrary data?",
    "text": "test post please ignore",
    "$type": "app.bsky.feed.post",
    "createdAt": "2023-04-17T20:12:06.676400836Z"
  },
  "indexedAt": "2023-04-17T20:12:07.048Z",
  "takedownId": null
} 
```

see `value->asd`

**Comment by bnewbold** [comment]
cc: @devinivy @dholms 

@jesopo did you set the `validate` flag when creating this record with the `asd` field?

I'm surprised if PDS allows creations like this without `validate=false`. Seems like a hardening oversight (on my part). Returning the record with all fields is the expected and correct behavior.

**Comment by jesopo** [comment]
i did not, i'll try it again with that flag

**Comment by jesopo** [comment]
`"validate": true` did not seem to help:

```
$ curl --header "Content-Type: application/json" --header "Authorization: Bearer redacted" "https://bsky.social/xrpc/com.atproto.repo.createRecord" --data '{"repo": "jesopo-test.bsky.social", "collection": "app.bsky.feed.post", "record": {"text": "test post please ignore", "createdAt": "2023-04-18T01:32:30.851900Z", "asd": "what does this button do"}, "validate": true}'
{"uri":"at://did:plc:sdeyff35uikqhp7tiu7p4dbd/app.bsky.feed.post/3jtmd7zjyal2m","cid":"bafyreic4sf3b6c22xwha6iiy7gg5ve6fduxgp7auxrmhvebs53qb6zuvwa"}
```
then

```
$ curl -s "https://bsky.social/xrpc/com.atproto.repo.getRecord?repo=jesopo-test.bsky.social&collection=app.bsky.feed.post&rkey=3jtmd7zjyal2m" | jq
{
  "uri": "at://did:plc:sdeyff35uikqhp7tiu7p4dbd/app.bsky.feed.post/3jtmd7zjyal2m",
  "cid": "bafyreic4sf3b6c22xwha6iiy7gg5ve6fduxgp7auxrmhvebs53qb6zuvwa",
  "value": {
    "asd": "what does this button do",
    "text": "test post please ignore",
    "$type": "app.bsky.feed.post",
    "createdAt": "2023-04-18T01:32:30.851900Z"
  },
  "indexedAt": "2023-04-18T01:33:38.637Z",
  "takedownId": null
}
```

**Comment by jesopo** [comment]
> I'm surprised if PDS allows creations like this without `validate=false`. Seems like a hardening oversight (on my part). Returning the record with all fields is the expected and correct behavior.

also of note, per the lexicon, `validate` is meant to default to true: https://atproto.com/lexicons/com-atproto-repo#comatprotorepocreaterecord

**Comment by bnewbold** [comment]
Thanks for following up!

**Comment by pfrazee** [comment]
We need @dholms and or @devinivy to chime in on this.

Last I checked, we don't strip additional off-lexicon keys because they're considered valid (for a variety of reasons including forward compatibility). Server-side validation is a somewhat contentious design choice right now since we haven't established whether the PDS is going to have lexicon knowledge in all cases. We've been using it now to reduce potential issues but it might right counter to protocol generality for other applications.

**Comment by jesopo** [comment]
thanks for the clarifiaction on policy!

**Comment by jesopo** [comment]
this does beg the question; it seems like `app.bsky.actor.profile` **does** strip extraneous keys - is that also intentional? if so, why the disparity?

**Comment by jesopo** [comment]
i swear i tried that before and it didn't work, but it does now. thanks all

**Comment by dholms** [comment]
Yup yup no worries! Gonna close for now, but feel free to hop in with any other questions
