### ISSUE TITLE
Match mention facet detection with handles definition

### ISSUE THREAD

**Issue by rithvikvibhu** [bluesky-social/atproto#833]
The definition for what's considered a valid handle says:

https://github.com/bluesky-social/atproto/blob/2360ffea62802e1f6d78f2a18c6aa9189d68e982/packages/identifier/src/handle.ts#L21-L22

But when detecting mentions in posts, RichText only finds domain names from a hard-coded list of TLDs:

https://github.com/bluesky-social/atproto/blob/2360ffea62802e1f6d78f2a18c6aa9189d68e982/packages/api/src/rich-text/detection.ts#L11-L16
https://github.com/bluesky-social/atproto/blob/2360ffea62802e1f6d78f2a18c6aa9189d68e982/packages/api/src/rich-text/detection.ts#L75-L83

It'd be nice the detection logic for mentions matches with `ensureValidHandle` instead of using a fixed TLD list, or even better for links too if `isValidDomain` switches from the fixed TLD list to an FQDN regex.

Context: for the https://stems.social server, Handshake TLDs aren't recognized when mentioning.

**Comment by rithvikvibhu** [comment]
Right, a server that doesn't resolve Handshake won't load that profile.

But this issue is about the inconsistency between what's allowed to be a handle and being able to mention that handle.

Say a user on bsky.social mentions @nonexistent.bsky.social. This should be a considered a handle even if the profile doesn't exist / doesn't resolve.

**Comment by dholms** [comment]
> Right, a server that doesn't resolve Handshake won't load that profile.

Handshake names are off-spec & not supported at the moment. This is similar to using a DID other than did:plc/did:web or a curve other than p-256/k-256. Of course, a service can publish whatever data they like, but they will lose the ability to interoperate with other services in the network. 

It's not impossible that Handshake will be supported at some point, but we want to limit complexity starting out & I'd encourage services to stay on spec. It will be disorienting for users if they find themselves in a separate ecosystem that cannot communicate with most atproto users.

> But this issue is about the inconsistency between what's allowed to be a handle and being able to mention that handle.

These functions fulfill different purposes. Handle validation within lexicons is more lenient, but in richtext detection, we only want to attempt to link handles that have a valid ICANN TLD.

**Comment by whyrusleeping** [comment]
> Say a user on bsky.social mentions @nonexistent.bsky.social. This should be a considered a handle even if the profile doesn't exist / doesn't resolve.

so that doesnt actually work because mentions resolve to a DID under the hood, and the post record is created with the mention referencing that DID. If the handle can't be resolved, the mention can't actually be created

**Comment by rithvikvibhu** [comment]
Ohh I see, that makes sense. Too bad it won't "just work". Thanks for the replies

**Comment by rithvikvibhu** [comment]
Handshake has a few gateways like hns.to, hns.is but we don't really recommend using them. All HTTP content passes through a single entity with the ability to read, modify, rewrite requests and responses. I assume this also applies to ENS gateways like eth.xyz.

I'd love to discuss this (and other naming systems too) - maybe GitHub Discussions?

P.S. stems.social already resolves ENS-based registries so technically folks can verify and use `*.eth` by adding the TXT record on chain - there's just no good UI for it yet (the official ENS website can't set DNS records, but the contract is compatible).
