### ISSUE TITLE
Add compression to endpoints with large payloads

### ISSUE THREAD

**Issue by devinivy** [bluesky-social/atproto#853]
The sync endpoints in particular could use some gzip compression.

Compression becomes worthwhile once the payload hits ~1kb.  On the sync routes we may not know the payload size in advance, so it's possible that this should be a feature of xrpc-server, potentially configurable per method or response.

**Comment by snarfed** [comment]
Yup. Sounds particularly useful for `com.atproto.sync`.

**Comment by dholms** [comment]
Yup that's exactly the motivation^^ Turns out repos (especially with history involved) compress _very_ well

**Comment by bnewbold** [comment]
Going to close as a dupe to consolidate conversation.
