### ISSUE TITLE
How long do refresh tokens last for?

### ISSUE THREAD

**Issue by ianklatzco** [bluesky-social/atproto#870]
Could I maybe get a pointer to where that's defined in code? 🥺 🙏

**Comment by ianklatzco** [comment]
`createRefreshToken` takes a `expiresIn` parameter:
https://github.com/bluesky-social/atproto/blob/a832c54de7d94e10b0fc8ac2c17746bd58190551/packages/pds/src/auth.ts#L63-L68

Which appears to have a default parameter of 90 days, if I'm understanding it correctly.

**Comment by dholms** [comment]
Yup yup that's right 👍 but you get a new refresh token on every refresh -- so you should stay logged in as long as you create a session at least once every 90 days

**Comment by devinivy** [comment]
One final detail: once a refresh token is used, it is revoked after a grace period.
