### ISSUE TITLE
Failed to fetch profile for invited users

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#873]
Bug report from app
![fail-inv](https://user-images.githubusercontent.com/4898225/233808494-30150d83-fa55-4321-bd20-9326d1db6e91.jpeg)
<img width="600" alt="Screen Shot 2023-04-22 at 5 08 28 PM" src="https://user-images.githubusercontent.com/4898225/233808513-89df75cd-9a31-4985-87ff-01665f7630ad.png">

**Comment by andrewumoh6** [comment]
Send me invite so I can check from my end

**Comment by bnewbold** [comment]
I'm pretty sure this is fixed, closing.
