### ISSUE TITLE
we are an organization of people with visual impairment and deafblindness we would like to try the application and see the accessibilities

### ISSUE THREAD

**Issue by discapacidad5** [bluesky-social/atproto#882]
Hello, we are an organization for people with visual disabilities and only blindness and we would like to test the application and see the accessibility in the application and suggest in that case the improvements would be They may give us an invitation code to enter and try it Our email is "discapacidad5@gmail.com

**Comment by dholms** [comment]
Sorry, Github issues is not the correct venue for invite request. We will not be fielding them there.
