### ISSUE TITLE
Creating records in some collections make them undeletable.

### ISSUE THREAD

**Issue by MichaelPriebe** [bluesky-social/atproto#902]
On my test account (@mikuhl.bsky.social) I accidentally created an additional profile record by creating one without the self rkey. It seems to not be able to be deleted.

**Comment by dholms** [comment]
What error do you get?

And what rkey is it at?

**Comment by dholms** [comment]
You'd need to do `deleteRecord` with the TID that it was given

**Comment by devinivy** [comment]
Closing as stale, we can reopen if we get some new info that points to a possible issue.
