### ISSUE TITLE
No sessions are affected by password changes

### ISSUE THREAD

**Issue by yafesdot** [bluesky-social/atproto#914]
Password cannot be changed from within the account settings in client applications in any way, but even if it's changeable from "I forgot my password," other sessions are not affected. With that, once the account is hacked/stolen, it is irreversibly accessible to others unless the administrators are contacted directly by the account owner. In fact, we can analyze this issue under a broader topic with such issues as insufficient auth options(like 2FA and Oauth) and the inability to manage logged devices. For now, I present it as a relatively narrow and probably easier-to-solve issue!

**Comment by devinivy** [comment]
This should be resolved— when a user changes their password all refresh tokens for the account are revoked.  If you continue to see this issue please feel free to reach out to me directly, my email can be found on my github profile.  Thanks!
