### ISSUE TITLE
@atproto/api docs are missing when published on NPM

### ISSUE THREAD

**Issue by dcsan** [bluesky-social/atproto#932]
these very helpful readme
https://github.com/bluesky-social/atproto/blob/main/packages/api/README.md

used to be visible when published to
https://www.npmjs.com/package/@atproto/api

but now I just see this:
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/514002/235350580-4106b383-7ef2-4fa2-9b6c-3a5020b0ba3f.png">

also it would be nice to link back to the repo if possible, tho maybe hard since the packages aren't separated here

**Comment by Matrix89** [comment]
It seems to be working rn, maybe npm had to refresh the cache or something.

There's also #895 which adds repo links to all `package.json` files, but it only links to the repo not to particular packages. According to [npm docs](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository) it's possible.
```json
{
  "repository": {
    "type": "git",
    "url": "https://github.com/facebook/react.git",
    "directory": "packages/react-dom"
  }
}
```

**Comment by dholms** [comment]
Looks like this one resolved itself fortunately
