### ISSUE TITLE
Curation/Moderation

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#94]
Write now the "indexing server" returns a simple linear timeline of content from a user's follows.

We should provide more options around curation & moderation.

This includes explicit block lists for users that you do not wish to interact with. Tooling to check "bad hash lists" for illegal content. And user-selected algorithms that allow a user to customize the sort of content they want - or do not want - to see if their feed.

**Comment by mikestaub** [comment]
Should this be done at the application level?

**Comment by whyrusleeping** [comment]
I think both at the application level and at the feed provider level. Every user should have the tools to give input into the content they see, and additionally feed providers should have the autonomy to select exactly what is being presented in their feed. This is the 'reach' portion of social that we've been talking about, and neither of those actions affects any individual users ability to post anything to their own 'store' (that is, their 'speech').
