### ISSUE TITLE
We do not support selling of codes & are looking into known cases where that is happening

### ISSUE THREAD

**Issue by wqyutv** [bluesky-social/atproto#940]
I’m not sure why my issue was closed and why I cannot reopen the original tread. The issue needs to be reopened. I don’t think it would be appropriate to discuss this any further in a public setting although if we could private message I can give @ names and I am not sure if you have the ability to see who issued a invite code.

              We do not support selling of codes & are looking into known cases where that is happening

_Originally posted by @dholms in https://github.com/bluesky-social/atproto/issues/934#issuecomment-1529130188_

**Comment by dholms** [comment]
You can email support at support@bsky.app
