### ISSUE TITLE
UCAN v0.10

### ISSUE THREAD

**Issue by chunningham** [bluesky-social/atproto#947]
The UCAN wg is on the precipice of [updating the specification to v0.10](https://github.com/ucan-wg/spec/pull/132). Does ATP plan to adopt the new version once an implementation is available?

**Comment by dholms** [comment]
We are hoping to do a revamp of atproto's auth system soon.

I helped write the spec for UCANs & am obviously a big fan of them :)

I think they would fit in nicely especially for service-to-service auth, but perhaps user auth as well.

We have research & design work to do before I can say one way or another. A major goal of atproto is to be as "web-y" as possible, so we're very cautious every time we introduce some technology that most webdevs are not aware of. 

Keep an eye on things!

Closing as this is non-actionable -- the discussion board may be a better place for future questions like this :)
