### ISSUE TITLE
Profile URLs do not support trailing slashes.

### ISSUE THREAD

**Issue by linesthatinterlace** [bluesky-social/atproto#964]
https://staging.bsky.app/profile/<handle> resolves to the BSky profile for @<handle>, if present.

https://staging.bsky.app/profile/<handle>/ does not - it returns a 404.

Other social sites make it work differently (I assume it's a simple alias or something).

https://twitter.com/<profile> and https://twitter.com/<profile>/ both work. I think twitch.tv, at least, also works like this.

It would be moderately nice if BSky worked this same way. I assume this is essentially a web client-level fix so hopefully an easy one.

**Comment by dholms** [comment]
Yup this is an issue on the client. I reposted over in our client repo so gonna close over here for now

**Comment by linesthatinterlace** [comment]
Ah sorry - I wasn't sure which repo was the client one. Could you point me that way?

**Comment by roj1512** [comment]
It’s apparently not public.
