### ISSUE TITLE
Do not allow publicsuffix domains as handles

### ISSUE THREAD

**Issue by dholms** [bluesky-social/atproto#969]
https://publicsuffix.org/list/public_suffix_list.dat

**Comment by dholms** [comment]
And maybe consider moving HTTP handle resolution to `.well-known`?

**Comment by dholms** [comment]
Or maybe consider this:

> How about putting in DNS record which flags for URL verification support? So if the domains added that record then the client would proceed to check this path but if the record isn't there it ignores it. Simplest way for a domain hosting people's handles on subdomains, I think

**Comment by SaphireLattice** [comment]
In addition to that, it really should not rely on subdomains to provide accurate info. Or well, subdomains of a domain under a public suffix. 

E.g. A handle of `subdomain.host.public-suffix` should cause the atproto to check with `host.public-suffix`, while `host.public-suffix` gets asked directly. 

> Could just limit public suffix list domains to only verify using DNS.
I guess you mean anything matching the suffix directly? Well, most of them are TLDs (or TLD-like, for when a country does not allow top-level registrations but has sub-TLDs), or services that allow almost anyone to get a subdomain... I guess it would work as a rule of thumb, but can honestly just deny anything matching directly.

**Comment by april** [comment]
Checking the PSL never hurts and has little downside, although it's unlikely (if possible) that someone will have control of a TLD or `_atproto.tld`.

> And maybe consider moving HTTP handle resolution to `.well-known`?

In my experience, I've typically only seen three methods for verifying domain ownership via HTTP served files:

1. putting it inside `/.well-known`
2. uploading a file to the root directory of the domain (not a directory, as directories are often mapped all over the place)
3. editing the default HTML file at the root of the website, e.g. adding a `<meta>` tag

All of which are done over HTTPS (which I assume you're doing but just putting it out there.)
