### ISSUE TITLE
resolveExternalHandle supports any domain allowing file access

### ISSUE THREAD

**Issue by Evalprime** [bluesky-social/atproto#979]
there's a user on bsky.social who has a handle of @s3.amazonaws.com because they were able to upload a file acting as an xRPC agent(?) using the resolveHandle endpoint.

I believe I've grasped why this is in here, to resolve handles to a DID where the handle may be present on an external service. unfortunately, you can also impersonate Amazon S3 using a fake xRPC bucket. if the goal here was to create a "file-based verification" system then a well-known URL is fine. but I take it that that's not what's happening here.

**Comment by ianklatzco** [comment]
This is intended:
![image](https://user-images.githubusercontent.com/1487413/236794249-c9f8ad1d-6e1f-4c76-bc03-eb3cb2455485.png)
[link](https://staging.bsky.app/profile/emily.bsky.team/post/3juuaipn3q424)

**Comment by Evalprime** [comment]
ok, this changes things (and some things I told other people lol)

xRPC is a protocol that *seems* like you'd need to run a server that serves xRPC, which isn't really user-friendly. I believe that the goal here is to work with xRPC seamlessly from resolveExternalHandle.

having this kind of file-based verification in well-known isn't ceding on anything and it wouldn't be that difficult to implement. you could probably have .well-known/did or something, or .well-known/atproto. and, of course, file servers won't serve .well-known, including s3.
