### ISSUE TITLE
use husky for pre-commit linting

### ISSUE THREAD

**Issue by Evalprime** [bluesky-social/atproto#984]
I submitted a pr here and I couldn't lint code until tests were ran after the pr was submitted. could we consider using [husky](https://typicode.github.io/husky/) for pre-commit linting?

**Comment by Matrix89** [comment]
> I couldn't lint code until tests were ran after the pr was submitted

This sounds like a real issue, pre-commit linting especially on bigger monorepos tends to get annoying, especially when you're doing atomic commits. IMO pre-push linting is a bit better but still meh

**Comment by Evalprime** [comment]
so I can actually lint before I commit in the repo itself but I still think we need husky

**Comment by dholms** [comment]
You should be able to run linting locally by running `yarn verify` (it's the same command that CI runs)

I don't really want to add `husky` right now because I don't want to lint the whole repo on every push
