### ISSUE TITLE
Is there a canonical spelling between ATProto vs Atproto ?

### ISSUE THREAD

**Issue by ianklatzco** [bluesky-social/atproto#997]
there's also `atproto` which seems sensible.

I like ATProto.

**Comment by roj1512** [comment]
This spelling thing is an issue.

**Comment by roj1512** [comment]
And the community prefers ATProto? 😂

**Comment by Evalprime** [comment]
yeah. if you were writing a Wikipedia article on the ATProto, it'd probably be called "AT Protocol", but if you want to keep it short, "ATProto" is fine

**Comment by bnewbold** [comment]
I don't think we have a final policy/request on this, but at least internally:

* in more formal contexts, "AT Protocol" or "Authenticated Transfer Protocol"
* in most casual contexts, "atproto" (lower-case). I guess "Atproto" at the start of a sentence or something, but meh.
* in variable names, either of "ATP" or "ATPROTO", or sometimes "at" as a prefix. eg, "AT URI"

**Comment by dholms** [comment]
yup @bnewbold nailed it 👍
